### ISSUE TITLE
Add CI build

### ISSUE THREAD

**Issue by japj** [microsoft/VS-PPT#10]
Add CI build, i.e. using AppVeyor (or something else).

This will also allow pull requests to be automatically verified, etc.

**Comment by justcla** [comment]
Not a bad idea. Thanks for the suggestion.

**Comment by adilmughal** [comment]
I am interested to do this but not sure how I can do that on main repository. I can fork and setup appveyor for that. I have experience of setting up CI with Jenkins and TFS but never did on Github. Any pointers?

**Comment by japj** [comment]
You could have a look at some of the extensions from Mads Kristensen. Plus the ExtensibilityTools extension provides an appveyor.yml you can use as a starting point. I recently also experimented with it, so can also help out if you want.

**Comment by justcla** [comment]
Thanks Japj. Good tip.
I'm setting up a build server on AppVeyor.
Will post again when it's up and running.

**Comment by LegalizeAdulthood** [comment]
@adilmughal To contribute a CI for a github project, it's just as you describe: fork your own repository, get the CI build working for that and then submit a pull request with your changes back to the original repo.  Easy-peasy!

**Comment by adilmughal** [comment]
Thanks @LegalizeAdulthood  and @japj. I get it now. Hey @justcla I am happy to give it a try... have you already started working on it?

**Comment by justcla** [comment]
Yes, I've started one here:
https://ci.appveyor.com/project/justcla/vs-ppt

Having trouble getting it to build though. I think we'll need to migrate the native references to NuGet references before it will build properly on AppVeyor.

Feel free to help out. Thanks!

**Comment by japj** [comment]
do you have the appveyor.yml in version control somewhere or are you using the appveyor portal to set this up?

**Comment by justcla** [comment]
I've been playing with a branch called VeyorConfig.
I checked in an appveyor.yml file under /src.

I also payed around with using the AppVeyor portal.

AppVeyor is currently building (on master) from the portal setup.

**Comment by japj** [comment]
I observed the following from the appveyor build logfile:

- IPeekBroker could not be resolved, I believe this is from Microsoft.VisualStudio.Language.Intellisense.dll from the VSSDK (and this interface might be new in VS2015 according to MSDN?)
- The AppVeyor build machine might have multiple versions of VisualStudio installed, since it has also found the "12.0" version of the above mentioned assembly

**Comment by justcla** [comment]
Ahh yes - multiple versions of VS are installed. And the error seen is symptomatic of that.
(Machines with only VS 2015 do not get this error.)

**Comment by japj** [comment]
There are some csproj files that contain ToolsVersion other than "14.0"
It could be that is triggering building with an older VS version

**Comment by justcla** [comment]
Can you play around with that and see if you have some success?

**Comment by japj** [comment]
I'll have a go in my branch at https://github.com/japj/VS-PPT/tree/appveyor, builds will be at https://ci.appveyor.com/project/japj/vs-ppt

**Comment by justcla** [comment]
Great. Thanks.

**Comment by japj** [comment]
ok, I also discovered that there are some roslyn binary dlls checked at src\Structure\BlockTaggerImpl\Roslyn

I believe those should be modified into nuget package references. 
Is that something you could look into?

**Comment by justcla** [comment]
Sounds about right.

Anyone could look into it, really. Hence the beauty of open-source! :-D

**Comment by adilmughal** [comment]
I have almost most of the references especially related to Microsoft.VisualStudio.Text.UI.WPF and Microsoft.VisualStudio.Shell.* and the dependencies to NuGet packages. However two questions:

1) GoToDef proj is now missing IWaitIndicator which was originally defined in Microsoft.VisualStudio.Language.Intellisense.Utilties which I am unable to find now. Now sure where it was previously coming from, can anyone know which namespace they belong now?

2) BlockTaggerImpl has a folder with Roslyn dlls. Do we have to depend on them or is it alright to go for NuGet packages?
