### ISSUE TITLE
Wrong report of errors in Solution Error Visualizer VS 2017 RTM

### ISSUE THREAD

**Issue by sergyu91ma** [microsoft/VS-PPT#103]
False errors reported. Check image. All 4 errors are false positive. The one in red you can see clearly that is false.  

![untitled](https://cloud.githubusercontent.com/assets/6949205/23827803/3e46bdea-06c5-11e7-8d33-49eb62959f4f.png)

**Comment by olegtk** [comment]
Well, Solution Error Visualizer just differently visualizes errors shown in the Error List. Are these false errors also displayed in the Error List?

**Comment by sergyu91ma** [comment]
i see yes. So this means it`s an VS 2017 intelissense bug? 

![image](https://cloud.githubusercontent.com/assets/6949205/23828083/6fd4b804-06ce-11e7-9ce4-86a8f4a1a876.png)

**Comment by olegtk** [comment]
Yes, if you believe the errors in the ErrorList are incorrect, please file a bug using Help/Send Feedback/Report a Problem. Thanks!

**Comment by ygoe** [comment]
@olegtk Have you tried starting a build and does the error persist? I often made the experience (albeit with C#) that the errors list isn't always updated when editing the code but only when explicitly building the project. I imagine this happens more often with C++.
