### ISSUE TITLE
Ctrl-Shift-Right is intercepted by Fix Mixed Tabs

### ISSUE THREAD

**Issue by moswald** [Microsoft/VS-PPT#112]
On my system, `Ctrl-Shift-Right` is supposed to extend the selection to the right by one word, but instead it causes the cursor to disappear. If I then hit `Enter`, my spaces are converted to tabs. This stopped happening when I disabled the Fix Mixed Tabs extension (although something is still intercepting the key combo, it no longer does anything).

**Comment by moswald** [comment]
More details: it apparently is eating both the `Alt` and `Ctrl` keys.

**Comment by justcla** [comment]
Woah. Weird. I'll see if I can repro it on my system.
Is this VS2015 or VS2017?

**Comment by moswald** [comment]
This is 2017.

**Comment by justcla** [comment]
I cannot repro this on VS2017 with FixedMixedTabs. My Ctrl+Shift+Right works perfectly.
Perhaps it's related to some other extension?

Have you tried resetting your keyboard bindings? (Tool->Options->Environment->Keyboard)

**Comment by moswald** [comment]
Yeah, resetting to default fixed it. Sorry guys, false alarm. I'm assuming there's some underlying bug in 2017 and disabling the FMT extension just made it manifest differently. ¯\\\_(ツ)_/¯

**Comment by justcla** [comment]
Excellent. Glad it got resolved. Now go up-vote PPT on the Marketplace. :-)
