### ISSUE TITLE
Can implement a Intellisecse/completion list that supports abbreviations?

### ISSUE THREAD

**Issue by CodingNinjaOctocat** [Microsoft/VS-PPT#119]
The current VS（2017） completion list is still not smart enough, and it does not support the abbreviation complete! For example: it does not support typing "mllc" to Complete "MyLongLongClass", and fortunately, you may want to type "mylong", unfortunately, you may want to type "mylonglongc" to complete. I hope that there should be a plug-in to support PascalCase, camelCase, S (s) Nake_C (c) ase abbreviation for code completion.

**Comment by justcla** [comment]
Thanks for the suggestion! This is not something that we're likely to build into PPT. But it's a great suggestion for the product teams.
I have passed the idea to the respective teams. Thanks for your input.

**Comment by justcla** [comment]
@CodingNinjaOctocat I'm sure you'll be pleased to see this....
Implemented in the Roslyn code base.

> Support camel cased matching, even if the pattern was entirely lowercase: [https://github.com/dotnet/roslyn/pull/18138](https://github.com/dotnet/roslyn/pull/18138)
