### ISSUE TITLE
TelemetryForPPT broken in current release

### ISSUE THREAD

**Issue by AdmiralSnyder** [Microsoft/VS-PPT#120]
after this error occured on another of my machines, too and People start to complain
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProductivityPowerPack2017

seems something went wrong with the upgrade for VS2017.1 ? this occurs since last week
Quoting:

The 'ErrorFilterPackage' package did not load correctly.
The 'PowerCommandsPackage' package did not load correctly.
The 'ColumnsGuidePackage' package did not load correctly.

The last one is particularly bad - it has the tendency to make VS crash completely.

Do they all depend on VSTelemetryForPPT? This one seems to want to disable itself all the time.

**Comment by markjhvt** [comment]
I've found that installing the extensions I want to use individually, as opposed to letting the main PPT extension install them, has worked better so far.

**Comment by markjhvt** [comment]
Nevermind... it started failing again.

**Comment by justcla** [comment]
@AdmiralSnyder Many (but not all) of the extensions depend on VSTelemetryForPPT.

@markjhvt @AdmiralSnyder 
Can this be reliably reproduced? If so, can you please describe the repro steps?

**Comment by markjhvt** [comment]
I didn't do much beyond just installing the extensions.  It often seems to work the first couple of times VS starts, but eventually it just starts failing.  Sometimes it doesn't start failing until I open a solution (I've used two different ones and that doesn't seem to make much difference).
I think the only other non-MS extension I have installed is from RedGate.  All the others were installed with VS2017.

**Comment by justcla** [comment]
Which extensions did you install?
Do some extensions get automatically disabled when VS starts? If so, which ones?

**Comment by markjhvt** [comment]
I had all the PPT extensions installed, but disabled (not uninstalled) the Ctrl-Click to Definition one.
VSTelemetryForPPT eventually disables itself (and would refuse to re-enable), at which point most of the others would start to fail.  I don't know what triggers VSTelemetryForPPT to disable - the first couple restarts of VS seem fine.
As of right now, I only have the Custom Document Well installed and working.  Though VSTelemetryForPPT has still been disabled automatically.

**Comment by justcla** [comment]
How can you tell when VSTelemetryForPPT is disabled?

Since the update, the only extension that directly includes Microsoft.VisualStudio.TelemetryForPPT.dll is the VSTelemetryForPPT extension.
If this is disabled, no extension will have access to the telemetry DLL.

This extension is embedded in 11 out of 15 PPT extensions.
It should be installed and enabled so long as any extension that depends on it is installed and enabled.

It looks like the system is automatically disabling the VSTelemetryForPPT extension.
We need to find out when this happens and why.

Does it show up in the Performance Monitor? (Help->Manage Visual Studio Performance)
Can you see it in the Extensions and Updates dialog?

Do you have any of the old PPT extensions (that directly included TelemetryForPPT.dll) still hanging around?

**Comment by markjhvt** [comment]
I see it in the Extensions dialog - it's labeled as Disabled there.
I do not see it in the Performance Monitor, but it is disabled at the moment.

I have not tried uninstalling that extension directly.  I have tried uninstalling all the other PPT extensions and reinstalling, but that didn't help.
I could try uninstalling (and reinstalling) everything, including VSTelemetryForPPT this time.

**Comment by justcla** [comment]
Yes, please try that. It should not be showing up in the Extensions dialog.

**Comment by markjhvt** [comment]
Well... it won't uninstall....
It goes through the uninstall process, but upon restarting VS, it's still there.

**Comment by markjhvt** [comment]
Just tried uninstalling via /safemode.  That seemed to do the trick.  Reinstalling the PPT extensions now....

**Comment by markjhvt** [comment]
Unfortunately, no luck... the VSTelemetryForPPT extension is gone, but the other PPT extensions are still failing.
The activity log has the same error: Could not load file or assembly Microsoft.VisualStudio.TelemetryForPPT, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by justcla** [comment]
@markjhvt We have tried repeatedly to replicate this at our end but have been unable to.

Can you please help us by identifying reliable repro steps?

We would like to eliminate the PPT Installer as a source of problems.
We would also like to eliminate PPT upgrade scenarios as a source of problems.
Therefore, could you try uninstalling all PPT extensions (please look very carefully and don't leave any hanging around). Also remove the PPT installer. Then Restart VS to ensure that all extensions are fully removed.
Then try manually installing each of the extensions (or a subset of the extensions).
If you encounter the error again, please take a note of what you were doing at the time, and which extensions were enabled/disabled.

If you can tell us how to replicate the error, then we'll be in a better position to fix it.
Thanks very much for your help with this. It is much appreciated.

**Comment by justcla** [comment]
@AdmiralSnyder Are you able to reliably reproduce this error? If so, can you please describe the repro steps?

**Comment by markjhvt** [comment]
Yeah, I can try individual extensions.
But at this point, my repro steps is really just to let the main PPT extension install the others.  Final restart once all the other extensions are installed seems fine.  Next restart after that, things start to fail.  I don't have a chance to do much more than that.
I'll send out a list of all the other extensions I have installed before I proceed with the PPT install, too.

**Comment by justcla** [comment]
> I'll send out a list of all the other extensions I have installed before I proceed with the PPT install, too.

That won't be necessary

> But at this point, my repro steps is really just to let the main PPT extension install the others.

Fair enough.

We'd like to know if the installer is causing the problems. Hence my request to try to repro by installing manually. If we still get the same problem when installing extensions manually, then we can assume it's not a problem with the installer.

**Comment by markjhvt** [comment]
Also, I do no have the 15.1 Update installed.  I've been avoiding that up to this point.

**Comment by justcla** [comment]
Why? 15.1 is full of important bug fixes.

**Comment by markjhvt** [comment]
I have no doubt, but I was trying to get this working before I did the update (I just noticed the update in my list of extension when all this started happening).

**Comment by justcla** [comment]
That's sensible. At least we know it's not related to the latest VS update. Good one.
Yeah the update just came out very recently. (I haven't updated yet.)

**Comment by markjhvt** [comment]
So far things are working!
I've installed the following ones individually:

Align Assignments
Custom Document Well
Double-Click Maximize
Editor Guidelines
Fix Mixed Tabs
Match Margin
Quick Launch Tasks
Power Commands for Visual Studio
Time Stamp Margin

So, if I remember correctly, my steps to get everything working were:
- uninstall all the extensions
- uninstall VSTelemetryForPPT via /safemode (step I hadn't done before)
- install PPT extensions individually, rather than via the main PPT installer

I've restarted VS a couple of times, loaded a couple different solutions.  And so far, no errors!

**Comment by justcla** [comment]
Good news. We'll keep digging to see if we can identify and fix the original problem.

**Comment by markjhvt** [comment]
Sounds good.... let me know if you need anything else

**Comment by justcla** [comment]
It appears that these problems only ever appear when the extensions are installed by the PPT installer. When installing the extensions manually, it seems we never get this error.

As a temporary solution, I plan to roll back to the previous version of all PPT extensions.

Then we can look at fixing the installer.

**Comment by justcla** [comment]
I have reverted all PPT extensions to the previous working version, but increased the version number so that auto-update will pickup the new extensions.

If you are experiencing upgrade problems, uninstall all PPT extensions, including the installer. Then delete the .productivitypowerpack2017 file from the user dir. Then reinstall PPT.

**Comment by AdmiralSnyder** [comment]
thanks, i'm gonna test it.

will the new "old" version apper in the VS [marketplace](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProductivityPowerPack2017) too? 
there the last update timestamp still is march 24th. 
it might be useful to update the version and timestamp whenever you do an update that will be fetched via autoupdate.

**Comment by marklnz** [comment]
I found that even after updating to the new/old versions of the PPT extensions (the ones the marketplace says is current), VS 2017 was still throwing a package load error for the OptionsPagePackage.

On checking my list of extensions I found that the VSTelemetryPPT extension was disabled, and re-enabling it made that error go away, with the most recent version of the PPT extensions from the marketplace.. 

So if anyone is still seeing the OptionsPagePackage load error after updating all the PPT extensions, go and make sure the telemetry extension is enabled.

**Comment by justcla** [comment]
Sounds like you have an out-of-date version of the PPTOptionsPage. The new PPTOptionsPage has no reference to VSTelemetryForPPT.
I suggest updating all four extensions that reference PPTOptionsPage:
- Ctrl+Click GoToDefn
- Match Margin
- Shrink Empty Lines
- Time Stamp Margin

**Comment by brianhaddock** [comment]
Battled this for most of the day.  VS crashes when opening a solution *if* PPT is installed.  Seems to occur after I patch Visual Studio (like today).  To fix, I uninstalled all the PPT extensions individually, then uinstalled PPT installer.  Deleted .productivitypowerpack2017 from the user directory.  Reinstalled PPT (the PPT installer installed all the sub-components after).  When prompted to restart VS, I received a cryptic dialog that simply said "unknown error" - not sure if that was related or not.  Started Visual Studio back up and could open the solution with no problem.

**Comment by justcla** [comment]
All PPT extensions have been updated - this time with no telemetry dlls and no telemetry MEF loading.
So hopefully that will put an end to this issue.

Please upgrade all extensions to remove the old versions that contained Microsoft.VisualStudio.TelemetryForPPT.dll.

If you have enabled auto-update for extensions (Tools->Options; Environment->Extensions and Updates->Automatically update extensions) then your PPT extensions will automatically be updated.
Note: Auto-update will not update disabled extensions. If you have extensions that aren't updating, check in Extensions and Updates to see if they have been disabled.

**Comment by AdmiralSnyder** [comment]
I just installed the Version currently online and everything seems fine.
