### ISSUE TITLE
The 'OptionsPagePackage' package did not load correctly

### ISSUE THREAD

**Issue by richardcox13** [Microsoft/VS-PPT#122]
Having updated to the latest Productivity Power Tools (in the hope of a fix for #120 I'm now getting this popping up shortly after the VS2017 IDE has loaded.

Latest PPTs are V15.0.2

From `activitylog.xml`:

> LegacySitePackage failed for package [OptionsPagePackage]Source: 'PPTOptionsPage' Description: Could not load file or assembly 'Microsoft.VisualStudio.TelemetryForPPT, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TelemetryForPPT, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.TelemetryForPPT, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at Microsoft.VisualStudio.PowerTools.OptionsPage.OptionsPagePackage.Initialize() at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]. 

It appears there is still a load problem with TelemetryForPPT.

**Comment by richardcox13** [comment]
NB. this is after updating to 15.1 (26403.03).

And it doesn't happen every time I start VS2017, but (so far) no pattern is apparent.

**Comment by jerone** [comment]
Having the same problem. Uninstalling all PTT extensions and installing it again solved it (for now).

> Microsoft Visual Studio Professional 2017 
> Version 15.1 (26403.3) Release
> VisualStudio.15.Release/15.1.0+26403.3
> Microsoft .NET Framework
> Version 4.6.01586

**Comment by justcla** [comment]
@richardcox13 Thanks for the feedback.
There are four extensions that embed the PPTOptionsPage VSIX:
- Ctrl+Click GoToDefn
- Match Margin
- Shrink Empty Lines
- Time Stamp Margin
The embedded PPTOptionsPage VSIX still contains a reference to the VSTelemetryForPPT VSIX, which contains the Microsoft.VisualStudio.TelemetryForPPT.dll.
I will reissue new versions of these four extensions that include a PPTOptionsPage that directly references the TelemetryDLL, instead of including it in the embedded VSTelemetryForPPT VSIX.
Hopefully that should solve the problem.

**Comment by marklnz** [comment]
Check also, after updating the PPT extensions, that the VSTelemetryPPT extension is enabled. For me it was disabled, and re-enabling it resulted in things working normally again.

**Comment by justcla** [comment]
If you've updated all the extensions, there should be no trace of the VSTelemetryForPPT extension.
The fix for issue #120 was to remove all instances of the embedded VSTElemetryForPPT vsix from all extensions. It should not be enabled or disabled - it should be completely removed.

**Comment by marklnz** [comment]
@justcla interesting - it wasn't removed for me, just disabled as I said. And again, enabling it resulted in the OptionsPagePackage error going away.

**Comment by justcla** [comment]
I realise that I didn't update the version of the PPTOptionsPage, so an update would have left the old one on your system (v2.0), and it refers to the problematic VSTelemetryForPPT extension (which I tried to eradicate in HotFix #120).
Uninstalling the 4 extensions above will completely remove the PPTOptionsPage and VSTelemetryForPPT. Then reinstalling them will install the updated PPTOptionsPage.

In the meantime, I am going to re-issue new versions of those four extensions, with references to an updated PPTOptionsPage.

**Comment by justcla** [comment]
I have uploaded new versions of the extensions that included the options page.
The updated versions are:
- [Ctrl+Click GoToDefn](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.CtrlClickGoToDefinition)  v15.0.4
- [Match Margin](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MatchMargin)  v15.0.3
- [Shrink Empty Lines ](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.SyntacticLineCompression) v15.0.3
- [Time Stamp Margin](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.TimeStampMargin)  v15.0.3

It is best to uninstall all four extensions (if installed), then reinstall the latest version.
This will remove the old v2.0 PPTOptionsPage extension and the associated VSTelemetryForPPT extension. It will install the new v15.0.1 options page, which includes the TelemetryForPPT dll directly.

**Comment by richardcox13** [comment]
@justcla OK did that.

- VSIX installer hung (close take from task manager needed) after uninstalling Matach Margin. In VS it had gone but needed to re-do uninstall of Shrink Empty Lines and Time Stamp Margin.
- Reinstalled (all versions have increment one higher than listed above)
- Still getting

> The 'OptionsPagePackage' package did not load correctly

and `ActivityLog.xml` has:

>  LegacySitePackage failed for package [OptionsPagePackage]Source: 'PPTOptionsPage' Description: Could not load file or assembly 'Microsoft.VisualStudio.TelemetryForPPT, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TelemetryForPPT, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.TelemetryForPPT, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at Microsoft.VisualStudio.PowerTools.OptionsPage.OptionsPagePackage.Initialize() at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].  

Is there any other information you need?

**Comment by richardcox13** [comment]
Repeating process:

- This time uninstrall hangs after shrink empty lines.
- Shrink empty lines has gone, but 2 remain.

  Seems 2nd one being uninstalled has a problem.

- After second cycle of uninstalls still getting option page package failing to load.
- Reinstalled just Shrink Empty Lines. Still getting options page package fail.
- Uninstall again. Still getting options page package fail. Clearly one of the four extensions has left something in place,
- End up uninstalling all of Prod. Power tools one by one (even a few at a time was hanging uninstaller)
- With all removed still getting load error. But see Productivity Power Tools Options Page now listed as extension. So removed that.
- Now don't get options page package fail.
- Adding the extensions I actually use...

No further errors yet...

**Comment by justcla** [comment]
@richardcox13 Thanks for the report. Much appreciated.

Seems you are having some issues with uninstalling multiple VSIXes.
And yes, completely uninstalling the old extension is essential.

I would be interested to know if you have trouble uninstalling other groups of extensions.
Perhaps the uninstaller issues are isolated to VSIXes with embedded VSIXes.
It would be interesting to test that by multi-uninstalling some of the other PPT extensions, which do not have embedded VSIXes.

**Comment by jerone** [comment]
When uninstalling all PPT extensions I too had hang on uninstall-dialog. Cancelling and then manually deleting the extensions in the extensions folder solved it. After starting VS the MEF tool kicked in and after that I was able to install the new PPT extensions again.

**Comment by richardcox13** [comment]
@justcla Noted... but currently need to focus on work rather than extensions :-( 

OTOH no further extension loading errors, so it is looking good.

**Comment by justcla** [comment]
I just uploaded a whole new set of PPT extensions. This time, I have removed the telemetry dll completely and there is no more MEF loading for telemetry, so there should be no more MEF cache invalidation/reloading issues due to mismatches telemetry dlls.
If you have auto-update enabled for extensions, your extensions will be automatically upgraded.

**Comment by franzalex** [comment]
@justcla 

I had hoped to fix my associated issue (#124) by updating to the latest version but the updates you [referred to](#issuecomment-294102088) do not seem to be live at the moment (2017-04-17 10:15).
![screen shot 2017-04-17 at 10 07 21](https://cloud.githubusercontent.com/assets/7560066/25086357/aa933048-2356-11e7-8153-e52c257ae0b1.png)

**Comment by justcla** [comment]
There was no change made to the [PPT Installer](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProductivityPowerPack2017).
Under the extensions installed by it changed.
Try reinstalling all the extensions. (Best to completely uninstall everything first, and delete the .productivitypowerpack2017 file from your user directory).

**Comment by verysimplenick** [comment]
@justcla 
I have similar issue. Can't go to extensions page, VS hung. Think I have disabled `VSTelemetryForPPT`. Latest activitylog.xml info:
```xml
  <entry>
    <record>731</record>
    <time>2017/05/29 18:31:39.990</time>
    <type>Information</type>
    <source>ClientRights</source>
    <description>Client rights determined: {&quot;CurrentClientRights&quot;:{&quot;ActivityId&quot;:&quot;410bb568-e607-4624-9d59-21f2b5692161&quot;,&quot;AuthorizedVsEdition&quot;:0,&quot;AuthorizedVsEdition2&quot;:200,&quot;CrtokenDaysToExpire&quot;:365,&quot;DaysSinceCreation&quot;:0,&quot;DaysToExpire&quot;:365,&quot;IsLicenseGood&quot;:true,&quot;IsSubscriptionBased&quot;:true,&quot;IsTrialLicense&quot;:false,&quot;LicenseDescription&quot;:&quot;Visual Studio Community&quot;,&quot;LicensedUserId&quot;:&quot;f8dd7604-b053-4797-83b5-ca54e5a14951&quot;,&quot;LicensedUserName&quot;:&quot;vovanchig@gmail.com&quot;,&quot;LicenseSource&quot;:1,&quot;LicenseSource2&quot;:1,&quot;LicenseStatus&quot;:4,&quot;LicenseType&quot;:17,&quot;LicenseUrl&quot;:&quot;&quot;,&quot;LicensingAccount&quot;:&quot;&quot;,&quot;MayUplevel&quot;:false,&quot;ReleaseType&quot;:1,&quot;RightsDaysToExpire&quot;:2147483647,&quot;RightsStatus&quot;:10,&quot;SubscriptionChannel&quot;:&quot;Free Program&quot;,&quot;ClientRightsMetadata&quot;:{&quot;SubscriptionChannel&quot;:&quot;Free Program&quot;,&quot;NonLocalizedLicenseDescription&quot;:&quot;VSCommunity&quot;,&quot;LicenseUrl&quot;:&quot;&quot;,&quot;ExpirationDate&quot;:&quot;\/Date(1527586796000)\/&quot;,&quot;ClientRightsVersion&quot;:{&quot;Major&quot;:15,&quot;Minor&quot;:0,&quot;Build&quot;:26430,&quot;Revision&quot;:6,&quot;MajorRevision&quot;:0,&quot;MinorRevision&quot;:6}}},&quot;CurrentLicenseSource&quot;:1,&quot;CurrentLicenseSource2&quot;:1,&quot;IDEUserClientRights&quot;:{&quot;ActivityId&quot;:&quot;410bb568-e607-4624-9d59-21f2b5692161&quot;,&quot;AuthorizedVsEdition&quot;:0,&quot;AuthorizedVsEdition2&quot;:200,&quot;CrtokenDaysToExpire&quot;:365,&quot;DaysSinceCreation&quot;:0,&quot;DaysToExpire&quot;:365,&quot;IsLicenseGood&quot;:true,&quot;IsSubscriptionBased&quot;:true,&quot;IsTrialLicense&quot;:false,&quot;LicenseDescription&quot;:&quot;Visual Studio Community&quot;,&quot;LicensedUserId&quot;:&quot;f8dd7604-b053-4797-83b5-ca54e5a14951&quot;,&quot;LicensedUserName&quot;:&quot;vovanchig@gmail.com&quot;,&quot;LicenseSource&quot;:1,&quot;LicenseSource2&quot;:1,&quot;LicenseStatus&quot;:4,&quot;LicenseType&quot;:17,&quot;LicenseUrl&quot;:&quot;&quot;,&quot;LicensingAccount&quot;:&quot;&quot;,&quot;MayUplevel&quot;:false,&quot;ReleaseType&quot;:1,&quot;RightsDaysToExpire&quot;:2147483647,&quot;RightsStatus&quot;:10,&quot;SubscriptionChannel&quot;:&quot;Free Program&quot;,&quot;ClientRightsMetadata&quot;:{&quot;SubscriptionChannel&quot;:&quot;Free Program&quot;,&quot;NonLocalizedLicenseDescription&quot;:&quot;VSCommunity&quot;,&quot;LicenseUrl&quot;:&quot;&quot;,&quot;ExpirationDate&quot;:&quot;\/Date(1527586796000)\/&quot;,&quot;ClientRightsVersion&quot;:{&quot;Major&quot;:15,&quot;Minor&quot;:0,&quot;Build&quot;:26430,&quot;Revision&quot;:6,&quot;MajorRevision&quot;:0,&quot;MinorRevision&quot;:6}}},&quot;PIDClientRights&quot;:{&quot;LicenseSource&quot;:0,&quot;LicenseSource2&quot;:0,&quot;IsSubscriptionBased&quot;:false,&quot;DaysSinceCreation&quot;:-1,&quot;LicenseType&quot;:2,&quot;AuthorizedVsEdition&quot;:0,&quot;AuthorizedVsEdition2&quot;:200,&quot;DaysToExpire&quot;:-1,&quot;IsLicenseGood&quot;:false,&quot;LicenseDescription&quot;:&quot;30 day trial (for evaluation purposes only)&quot;,&quot;LicenseStatus&quot;:-1,&quot;LicenseUrl&quot;:&quot;&quot;,&quot;MayUplevel&quot;:false,&quot;LicensedUserId&quot;:&quot;00000000-0000-0000-0000-000000000000&quot;,&quot;LicensedUserName&quot;:&quot;&quot;,&quot;LicensingAccount&quot;:&quot;&quot;,&quot;ReleaseType&quot;:1}}; Account identity provider: MSA</description>
  </entry>
  <entry>
    <record>732</record>
    <time>2017/05/29 18:31:40.197</time>
    <type>Information</type>
    <source>UserConnection</source>
    <description>user authentication successful for IDE user</description>
  </entry>
  <entry>
    <record>733</record>
    <time>2017/05/29 18:31:41.929</time>
    <type>Information</type>
    <source>UserConnection</source>
    <description>vovanchig@gmail.com signed in for IDE user</description>
  </entry>
  <entry>
    <record>734</record>
    <time>2017/05/29 18:31:43.524</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function CVsPackageInfo::HrInstantiatePackage</description>
    <guid>{30D5B2E6-64BF-422F-A2BF-5D5B4D66548F}</guid>
  </entry>
  <entry>
    <record>735</record>
    <time>2017/05/29 18:31:43.524</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Unexpected system error mode before loading package [Settings Store Synchronization Delayed Init Package]</description>
    <guid>{30D5B2E6-64BF-422F-A2BF-5D5B4D66548F}</guid>
  </entry>
  <entry>
    <record>736</record>
    <time>2017/05/29 18:31:43.524</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Settings Store Synchronization Delayed Init Package]</description>
    <guid>{30D5B2E6-64BF-422F-A2BF-5D5B4D66548F}</guid>
  </entry>
  <entry>
    <record>737</record>
    <time>2017/05/29 18:31:43.524</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Settings Store Synchronization Delayed Init Package]</description>
    <guid>{30D5B2E6-64BF-422F-A2BF-5D5B4D66548F}</guid>
  </entry>
  <entry>
    <record>738</record>
    <time>2017/05/29 18:31:43.525</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function CVsPackageInfo::HrInstantiatePackage</description>
    <guid>{D177414D-2D6A-49F2-8497-C51A2629846B}</guid>
  </entry>
  <entry>
    <record>739</record>
    <time>2017/05/29 18:31:43.525</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Appid denied the loading of package</description>
    <guid>{D177414D-2D6A-49F2-8497-C51A2629846B}</guid>
  </entry>
  <entry>
    <record>740</record>
    <time>2017/05/29 18:31:43.525</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Package failed to load; error message suppressed by skip flag</description>
    <guid>{D177414D-2D6A-49F2-8497-C51A2629846B}</guid>
  </entry>
```

**Comment by justcla** [comment]
Try completely uninstalling all PPT extensions. There should be so instance of the VSTelemetryForPPT extension anywhere anymore. If you have it, then you must have an old copy of one of the extensions.
It won't go away until all extensions that once referred to it have been uninstalled.

**Comment by verysimplenick** [comment]
Yep, finally I repair VS to uninstall all extensions, but problem not disappear. Now I can't install any extension. Something wrong in VS. [I did post bug](https://developercommunity.visualstudio.com/content/problem/62609/visual-studio-hangs-when-try-open-extensions-toolb.html). You can see perfview dump there.

**Comment by verysimplenick** [comment]
@justcla found solution, need run this services:

```bat
net start NcdAutoSetup
net start NlaSvc
net start netprofm
```

**Comment by justcla** [comment]
Thanks. I think I'll close this issue now.
