### ISSUE TITLE
Align Assigments not working in vs2017 v15.2 and vs2017 15.3 preview 4.0 in a C# file

### ISSUE THREAD

**Issue by gernotpokorny** [Microsoft/VS-PPT#145]
I also tried the suggested fix

> Note! This may conflict with your formatting settings. E.g. in C# you will need to disable: Tools->Options->Text Editor->C#->Formatting->Spacing->"Ignore spaces in declaration statements"

But it is still not working.

**Comment by justcla** [comment]
Why isn't it working?

**Comment by gernotpokorny** [comment]
I don't know. I tried it in vs2017 v15.2 and in v15.3 preview 4.0

**Comment by justcla** [comment]
Is it installed?

How to check:
- Does it show up in Tool->Extensions and Updates?
- Is it enabled?

![image](https://user-images.githubusercontent.com/17131343/28484085-6dcba18a-6e25-11e7-8b23-6be045514b1c.png)

- Do you see a command in Tools->Options; Environment->Keyboard; for "Edit.AlignAssignments"?

![image](https://user-images.githubusercontent.com/17131343/28484070-4c80c910-6e25-11e7-87a9-915e5cb5e6e1.png)

- Are there other commands bound to Ctrl+Alt+] ?
- Are you using the ENG US keyboard mapping (or some international keyboard layout)?

**Comment by gernotpokorny** [comment]
Ok with your help I found the problem. It automatically predefined another shortcut instead of the "Ctrl+Alt+]"-shortcut. Maybe because this shortcut was already occupied. Please have a look at the following images.

![align_assignemnts-extensions](https://user-images.githubusercontent.com/20481193/28484302-dabe9814-6e71-11e7-98b3-c76456dd3ec3.png)
![align_assignemnts-options](https://user-images.githubusercontent.com/20481193/28484303-dac6c430-6e71-11e7-8860-3ca38c2ca4f9.png)

**Comment by justcla** [comment]
Nice one.
We don't randomly assign keyboard shortcuts.
BUT....If you are using a different keyboard layout scheme, that could affect it.
This command is assigned to VK_OEM_6 (with Ctrl+Alt).
On the standard US keyboard layout, VK_OEM_6 is the "] }" key.
But other keyboards define it differently.
For instance, if you're using the Belgian keyboard, it assigns it to Ctrl+Alt+^.
(See this issue about that: https://github.com/Microsoft/VS-PPT/issues/69)

Check under Windows Settings->Region & Language, Languages.
I have the English (United States) language.
![image](https://user-images.githubusercontent.com/17131343/28484538-d2abe658-6e27-11e7-8f3c-c71570460d96.png)

Go into the Options to see which keyboard layouts are defined.
![image](https://user-images.githubusercontent.com/17131343/28484553-e296ad1e-6e27-11e7-8164-238126559af3.png)

If you have more than one keyboard layout defined, you should see the current layout in the right corner of the Windows task bar.
Clicking it gives you the option to change layouts.
![image](https://user-images.githubusercontent.com/17131343/28484608-2114f276-6e28-11e7-877a-073f0f81f0b0.png)

Try it with ENG US and see what you get in the Tools->Options;Keyboard.

**Comment by gernotpokorny** [comment]
These are my settings:

![align_assignemnts-region](https://user-images.githubusercontent.com/20481193/28485009-82763ab8-6e76-11e7-881c-19a44e2794f4.png)
![align_assignemnts-region-options](https://user-images.githubusercontent.com/20481193/28485008-827317f2-6e76-11e7-875e-911fe07fbb16.png)

Just to let you know (it is so important for me, since I'll redefine the shortcut anyway, because I'm using a german keyboard layout), I also tried it with the ENG US layout (see the following image) with the default shortcut (Ctrl+Alt+] ), but it is not working. Maybe it's because my language is set to English (United Kingdom) and yours is set to English (United States).

![align_assignemnts-keyboard_mapping2](https://user-images.githubusercontent.com/20481193/28485066-0ba8a758-6e77-11e7-9060-0df515fb1c42.png)

**Comment by justcla** [comment]
OK - Well it seems we've found the issue.
We bind the command to VK_OEM6. This represents different keys on different keyboards.
On the ENG US keyboard it will be right square bracket. If you're using another keyboard, it is likely to be a different key.
You can either switch to the ENG US keyboard, which will result in VK_OEM6 being the right square bracket, or you can use the alternative key for whichever keyboard you're using.
Or you can re-map it.

Please confirm that if you use the shortcut that is visible in Tools->Options;Keyboard, (whatever that might be) that the command runs.

**Comment by gernotpokorny** [comment]
> Please confirm that if you use the shortcut that is visible in Tools->Options;Keyboard, (whatever that might be) that the command runs.

I confirm.

**Comment by justcla** [comment]
Thanks.

Note:  "It automatically predefined another shortcut"

No. It assigns it to whatever key is on VK_OEM6 - and that is defined by the keyboard layout in use.
Clearly, the German keyboard layout has VK_OEM6 set to `.
The Belgian keyboard sets it to ^.
The ENG US keyboard sets it to ].
