### ISSUE TITLE
Change highlight word color

### ISSUE THREAD

**Issue by farzadmf** [Microsoft/VS-PPT#148]
Hi,
First of all, thank you for this great extension. There is one thing I couldn't figure out how to do. When we enable the option **show matches in the editor**, is there a way to change the color? I tried all the "Highlight" options (i.e., **Highglight (Definition | Parameter | Reference | ...)**, but none of them seems to change the highlighting. Do I need to restart Visual Studio for changes to take effect, or is there another setting that I should change?

Thank you

**Comment by justcla** [comment]
Hi. Thanks for your kind words.

Try this solution from David Pugh:

> The match margin color is named “Match color”.
> Foreground color == color of the mark in the margin
> Background color == color of the highlight in the editor.

**Comment by farzadmf** [comment]
Hi, and sorry for the very late reply.
First of all, thank you for your answer, and secondly, I'm not sure if I'm missing something, but I don't seem to be able to find out which extension you're referring to

**Comment by justcla** [comment]
Hi. I didn't refer to any extension.

PPT bundles an extension called "Match Margin". It creates little markers on the scrollbar to indicate the location of all the tokens that match the one that the caret is on.
And you can change the color of those markers by adjusting the color of the "Match color".

If you are talking about the feature where matching items are highlighted in the editor window (not the scrollbar), that feature comes standard with Visual Studio and has nothing to do with any extensions (including PPT).

**Comment by justcla** [comment]
I found that I could change the color of the highlighted matching items by modifying settings in Tools->Options; Fonts and Colors.

![image](https://user-images.githubusercontent.com/17131343/29692392-9b9bd6aa-88e4-11e7-9769-c687f613b826.png)

Notice in the screenshot provided that that highlighted items span several different color types, so you might want to set them all equally (unlike my example where I set Highlighted Definitions to red, Highlighted Reference to purple and Highlighted Written Reference to yellow).

**Comment by farzadmf** [comment]
Hi, I recorded a GIF to show what happens in my case in Visual Studio 2015.

![highlightcolor](https://user-images.githubusercontent.com/5768792/29745920-43455e50-8a96-11e7-9fe6-d7672e2f1bfc.gif)

As you can see, I have set all the "Highlighted ..." options to weird colors to make them stand out. When I click on `model` in `Create` method, the ones in `Edit` method are also highlighted, but that color cannot be changed; also, when I click on `newRestaurant`, the one in the comment is also highlighted, again with a color that cannot be changed either.

I don't have this one in the GIF, but when I uncheck the **Show matches in the editor** for Productivity Power Tools (in the **Other Extensions** section), those "un-changeable" highlights do not appear anymore (`model` in the other method, and `newRestaurant` in the comment). Maybe it's another extension responsible for those highlights, but why are they gone after I disable the option in PPVT?

**Comment by justcla** [comment]
Thanks for the GIF and the detailed analysis.
I will look into this further.

**Comment by farzadmf** [comment]
My pleasure.
Looking forward to hear back from you :)

**Comment by justcla** [comment]
I've figured it out.
When you click "model" in the Create method, it highlights all occurrences of that variable. (That is, the actual variable in that method - not different variables in other methods with the same name.)

![image](https://user-images.githubusercontent.com/17131343/29786547-68bb6094-8be0-11e7-99ef-a9bf09c2cefa.png)

Notice how the margin shows there are many matches of that text string, but they are not highlighted in the editor.

When you enable Match Margin's feature to **Show matches in the editor**, it starts highlighting all matches of that text string - including those matches in other methods.

![image](https://user-images.githubusercontent.com/17131343/29786525-57278696-8be0-11e7-94ae-eae43c3ee7b5.png)

See how the text string "theme" is now highlighted in more places.

![image](https://user-images.githubusercontent.com/17131343/29786431-fd68cb06-8bdf-11e7-8ef8-375525fa6e81.png)

Notice how there are new highlights (cyan colored) for other matches.

You can set the color of these other matches (introduced by Match Margin - Show matches in editor) by modifying the "Match color" color in Fonts and Colors.

![image](https://user-images.githubusercontent.com/17131343/29786646-db446a02-8be0-11e7-97a0-8ac2b5ff6de1.png)

Hopefully that solves the issues you were having.

**Comment by farzadmf** [comment]
Oh, finally! Thank you so much :) It's been a long time I tried to change those colors, because I think the feature itself is useful, but the colors were actually annoying and I wanted to change them. Thank you again :)

One more question: are the colors for the margin customize-able too? Can we change it to be something else other than the default purple?

**Comment by justcla** [comment]
It keeps coming back to David's original words. I think he got it all in the first go.

> The match margin color is named “Match color”.
Foreground color == color of the mark in the margin
Background color == color of the highlight in the editor.

It looks like we re-use the "Match color" foreground for both editor text color and margin marker color.

**Comment by farzadmf** [comment]
Thank you for the answer....
And you're right; t seems that the first answer pointed out the **Match Color** option; sorry I think I missed it. 

But anyway, I'm so happy that I know what's happening with the colors!

**Comment by justcla** [comment]
Correction: Match color foreground does not affect the foreground of the text for highlighted items in the editor.
It is ONLY for the markers on the margin.
There is no way to set the foreground color of highlighted items in the editor (for these string matches introduced by the Match Margin extension.)

**Comment by farzadmf** [comment]
Thank you for your help. I'm closing this as this is resolved.
