### ISSUE TITLE
CollapseRegions and ExpandRegions do nothing

### ISSUE THREAD

**Issue by ygoe** [Microsoft/VS-PPT#151]
Visual Studio 2017, 15.3.2, Windows 7 x64. This worked in Visual Studio 2015 and I use it a lot.

Oh, this seems to be a repository for everything, so here's what I'm talking about and what links here:
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.QuickLaunchTasks

**Comment by justcla** [comment]
I have tested the latest version and can confirm that @task CollapseRegions performed a no-op.
Similarly, ExpandRegions did nothing.

Needs investigation and fix.

**Comment by prnadago** [comment]
Closing issue as resolved.
