### ISSUE TITLE
Out of Date Roadmap

### ISSUE THREAD

**Issue by spottedmahn** [Microsoft/VS-PPT#169]
The [roadmap](https://github.com/Microsoft/VS-PPT/wiki/Roadmap) hasn't been updated in almost 2 years.  Is the project still active?

![image](https://user-images.githubusercontent.com/14079228/35744872-78909150-080f-11e8-8661-e64a3729e24b.png)

**Comment by justcla** [comment]
It's as active as it's ever been.
That being said, it's never really been that active. There is no official development being done for PPT. We occasionally fix bugs as they are identified by users.
