### ISSUE TITLE
[Custom Document Well] Color tabs by ASP.NET areas

### ISSUE THREAD

**Issue by jerone** [microsoft/VS-PPT#178]
I would like to suggest another coloring option: **color tabs by ASP.NET MVC/Core project areas**.

Instead of working with multiple projects, we work with different areas in one single project. This means that all tabs have the same color. An option to show different color depending in which area the file is located would make it easier to detect.

For example the following project structure:
* ASP.NET project
  * Areas
    * Admin
      * Views
        * Home
          * HomeController
    * Customer
      * Views
        * Home
          * HomeController
  * Views
    * Home
      * HomeController

If I open all three HomeControllers, there is no distinction between them.

**Comment by justcla** [comment]
Great suggestion! Thank you.
I can see how useful that would be.

But help me out... How would we determine what area a file is in? And how would colors be assigned to the areas? Would users pre-define areas and their colors? Or is there another way you figured to automatically assign colors?

**Comment by justcla** [comment]
If each area is in its own folder or has a common folder structure, could you use the regEx matcher to color by file path?

**Comment by jerone** [comment]
The folder structure of an area is fixed. So based on the "full document path" this could be styled. Any file below an area is then colored.
My suggestion would be to add an extra setting in Productivity Power Tools > Custom Document Well > General, under Tab Appearance. This setting would have higher priority of project colors, so files not under an area (e.g. Global.asax.cs) are still colored based on project.

Fixed folder structure of ASP.NET project areas:

* ASP.NET project
  * Areas
    * Area 1
    * Area 2
    * Area ...

**Comment by jerone** [comment]
[**@justcla**](https://github.com/justcla) commented on [Apr 10, 2018, 7:18 PM GMT+2](https://github.com/Microsoft/VS-PPT/issues/178#issuecomment-380179881 "2018-04-10T17:18:46Z - Replied by Github Reply Comments"):
> If each area is in its own folder or has a common folder structure, could you use the regEx matcher to color by file path?

You can use an regex, but you need to create an regex for every area name, to color every area with a different color. It's not possible to distinct different areas with just one regex. For example the following regex's<sup>1</sup> are needed based on previous folder structure:
* `.*/Areas/Admin/.*`
* `.*/Areas/Customer/.*`

<sub>1) The option Productivity Power Tools > Custom Document Well > Advanced > "Use full document path for regular expression matching" need to be checked.</sub>

**Comment by justcla** [comment]
Ah, yes. That's just what I meant. And why I was asking about what you had in mind.

> And how would colors be assigned to the areas?
> Would users pre-define areas and their colors?
> Or is there another way you figured to automatically assign colors?

So, yes. It seems you can manually define colors per area using the regEx (if you check the option to use full document path - nice find, thanks)

Sounds like you're looking for automatic color rules - like we provide for Project, so it works for all your solutions without any need to hard code the area names and colors into your VS settings.
I can see that being useful.

In the meantime, I suppose the workaround is to manually create hard-coded regEx expressions and colors to suit the areas in your project.

If we ever do more work in this area, we'll definitely look at introducing the automatic Area detection and coloring. Cheers.

**Comment by jerone** [comment]
> Sounds like you're looking for automatic color rules - like we provide for Project, so it works for all your solutions without any need to hard code the area names and colors into your VS settings.

👍

**Comment by MarkIvanDev** [comment]
Is there a chance that the color can be based on namespace? Since namespace is most likely based on the folder structure of a project? This feature is really helpful for those of us working on massive projects. Thank you
