### ISSUE TITLE
PPT Options page not visible in Tools->Options

### ISSUE THREAD

**Issue by justcla** [Microsoft/VS-PPT#182]
Question from user: Cheikh Ndiaye on Marketplace Q&A:

I have visual studio 2017 version 15.6.7 but after installing PPT i'm not able to see it in the Tools -> Options menu. I've tried uninstall, install and reset PPT several times but still not fixed.
I also found the github project in the following link : https://github.com/Microsoft/VS-PPT but the given link in there to download "PPT Options Page" is not working. Is there a solution or something i can try to fix that?

**Comment by justcla** [comment]
Cheikh,

Under Tools->Extensions & Updates, if you search in the "Installed" tab for "PPT" (top right search box), which extensions show up?
(There should be around 15 separate extensions, plus the PPT installer.)

Are any of them disabled?

**Comment by tancndi** [comment]
Justin, 
By searching "PPT" in the "installed" tab i dont see any of the extensions. I even don't see  the productivity power tool whereas I installed it.

![image](https://user-images.githubusercontent.com/30246568/39365992-b06112f2-4a00-11e8-8ace-4ac9666022db.png)

**Comment by justcla** [comment]
Are you sure it installed? Can you find any of the PPT extensions in your Installed list?
If not, then that might explain why no options appear.

I recommend re-installing PPT.

The PPT installer is sometime flaky. DO avoid using the PPT installer. Instead, individually install the extensions that you want on your system. You can find the list of PPT extensions on the details page in Marketplace.

**Comment by tancndi** [comment]
I've it installed actually:
![image](https://user-images.githubusercontent.com/30246568/39378375-37eb8fd4-4a26-11e8-8b01-8298b93a540e.png)

i noticed that not all the extensions are also installed but only three of them are enabled : 
- Productivity Power tool 2017
- Quick Launch Task
- Fix Mixed Tabs

Is there an extension that allow to display the tools in the Tools-> Options menu ?
Should I  enable all of them ?

**Comment by justcla** [comment]
Which options are you looking to change?

You only get the options page if you have installed one of the four (4) extensions that need options. I think that includes Ctrl+Click GoToDefn, Timestamp Margin, Match Margin and ... one other.

There is no Options page for turning the features/extensions on and off. You do that by enabling/disabling the extensions via Tools->Extensions & Updates now.

**Comment by tancndi** [comment]
Actually the option i was looking for was on Power Command extension. In fact I just had to enable the extension.
I wanted to have the following options :
![image](https://user-images.githubusercontent.com/30246568/39380461-a410baf8-4a2c-11e8-88d1-d01ee3e3a3e3.png)

It works fine. 

Thank you

**Comment by justcla** [comment]
Excellent. :-)

Can you please update the Marketplace Q&A to inform users of the solution to your problem. In this case:
- Some PPT extensions get disabled, and then their options won't show up in Tools->Options. To fix, go into Tool->Extensions & Updates and enable the extensions you want to use.

**Comment by tancndi** [comment]
Ok perfect. Thanks again.
