### ISSUE TITLE
CopyAsHtml font-size property. Explicitly specify the unit of measurement - pixels.

### ISSUE THREAD

**Issue by kirsan31** [Microsoft/VS-PPT#183]
CopyAsHtml calculate CSS property `font-size` in pixels, but it's not specifying strictly as `px`. So, some of html renders didn't understand it correctly. For example:
Current: 
`font-size:12` 
Need to be: 
`font-size:12px`

**Comment by justcla** [comment]
Nice pick-up.
The code is open-sourced. Any chance you could make the change and submit a PR?

**Comment by justcla** [comment]
What's the fix?
If you submit a PR, I can try building it. I have a working copy that builds.

**Comment by kirsan31** [comment]
https://github.com/Microsoft/VS-PPT/blob/master/src/CopyAsHtml/CopyAsHtml/HtmlMarkupProvider.cs
line 332:
```c# 
styles.Add("font-size", currentSize);
```
to
```c#
styles.Add("font-size", currentSize + "px");
```

I just built the project and checked - everything works. If I have time, I will make PR ...

**Comment by kirsan31** [comment]
Done. https://github.com/Microsoft/VS-PPT/pull/184

**Comment by justcla** [comment]
Terrific! Thanks @kirsan31  :-D

**Comment by kirsan31** [comment]
You can save it from notepad to *.html and then check in browser. But, as I know, most of them automatically assume px, if units not specified. For checking, I used qt controls like qlable and qtextedit. They use strict css styles and don't understand font-size without units.
P.s. Sorry, I am from phone now.
