### ISSUE TITLE
Release notes missing

### ISSUE THREAD

**Issue by tibel** [Microsoft/VS-PPT#207]
There are no release notes for versions afer 15.0.5

Also there are no commits to this repo since 5 month.
Is the [Marketplace](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MatchMargin) updated from some other (internal) repo?

**Comment by justcla** [comment]
Only part of PPT is open-sourced here on GitHub. The rest of it is held in our private repo. We build from our internal repo.

The PPT extension itself is just an installer and is unlikely to be updated. The individual extensions should keep up-to-date release notes.
