### ISSUE TITLE
Match Margin Issue in 15.8.8

### ISSUE THREAD

**Issue by Daskie** [Microsoft/VS-PPT#211]
Since upgrading to Visual Studio Community 15.8.8 I am now encountering an issue with the Match Margin extension.

When I start Visual Studio, I get a popup that says:
`An exception has been encountered. This may be caused by an extension.`

Followed by a popup that says:
`The 'OptionsPagePackage' package did not load correctly.`

When opening a solution, I get:
`The 'Microsoft.VisualStudio.Editor.Implementation.EditorPackage' package did not load correctly.`

When attempting to open a file, I get:
```
No EditorOptionDefinition export found for the given option
name: Adornments/HighlightCurrentLine/Enable
Parameter name: optionId
```
and the file does not open.

And when I go into options -> Productivity Power Tools (-> General), I get a blank page.

I am fairly sure Match Margin is the culprit. Simply disabling it fixes the issue. Additionally, I have uninstalled all extensions - the issue goes away - then installed only Match Margin - the issue returns. I have tried clearing the cache as well.

**Comment by Daskie** [comment]
Issue persists in 15.8.9

**Comment by Danielwbolson** [comment]
Issue persists in 15.9.1

**Comment by Daskie** [comment]
Works again in 15.9.2, thankfully! Microsoft, please.
