### ISSUE TITLE
Document peeking on Ctrl+Click no longer functions

### ISSUE THREAD

**Issue by fuj1n** [Microsoft/VS-PPT#213]
Since I updated, Ctrl+Clicking no longer opens up the little peek popout, and searching for "peek" in settings shows the "Productivity Power Tools" general menu, but there is nothing there mentioning peek

![image](https://user-images.githubusercontent.com/4004193/49593570-fc35ea00-f9c7-11e8-86b3-520100838b2d.png)

**Comment by prnadago** [comment]
Hey @fuj1n - so we've actually deprecated the Ctrl+click gtd extension in VS 2019 because it's built into the product now :)
You can change the setting by going to Tools > Options | Text Editor | General.

**Comment by fuj1n** [comment]
Oh, thank you, didn't know peek was still an option in the new behavior
