### ISSUE TITLE
Document Well not available in VS2019 Preview

### ISSUE THREAD

**Issue by lniedzielski** [microsoft/VS-PPT#222]
Document Well works well in VS2017 and does not for me in VS2019 Preview 3. It seems like it's not installed - no trace of it in VS Extensions and neither in Options for PPT:

![image](https://user-images.githubusercontent.com/1392640/53005374-6d1b6880-3433-11e9-8348-f27161517acf.png)

**Comment by TeaDrivenDev** [comment]
This is crucial and the most important part of PPT by a massive margin. However, this repository doesn't even seem to contain the code for the extension. Should this remain missing, that would be an extremely disappointing development.

**Comment by olegtk** [comment]
We are investigating, thanks for reporting this...

**Comment by prnadago** [comment]
Also - Please upvote this ticket on Developer Community if you would like this extension supported in VS 2019 - https://developercommunity.visualstudio.com/idea/465490/update-support-for-custom-document-well-to-visual.html

**Comment by alelom** [comment]
No updates on this? I miss this feature so much!

**Comment by alelom** [comment]
> Also - Please upvote this ticket on Developer Community if you would like this extension supported in VS 2019 - https://developercommunity.visualstudio.com/idea/465490/update-support-for-custom-document-well-to-visual.html

For reference, this was closed with [this message](https://developercommunity.visualstudio.com/t/Update-support-for-Custom-Document-Well/465490#T-ND477181): 

>  Due to our own restrictions in the product regarding asynchronous loading [...] and the way that Custom Document Well works, we've come to the conclusion that we cannot update the extension and continue to support it in Visual Studio 2019. So instead, we're looking into bringing the most popular features of the extension into the product. 

So the issue was split in multiple other issues, e.g. the grouping in one issue, the colouring by regex in another, etc. The plan to incorporate them in the main product is already well underway it seems, but sadly that is only for VS2022, and VS2019 is not covered. This leaves VS2019 without that beloved feature.

**Comment by alelom** [comment]
I found a workaround here: https://superuser.com/questions/1421557/can-i-install-the-custom-document-well-vertical-tabs-extension-for-visual-stud#_=_

**Comment by olegtk** [comment]
Sorry, the Document Well extension has been incorporated into VS 2022 and no longer supported as an extension.
