### ISSUE TITLE
Copy As Html 2022: Missing Edit > Copy Html Markup

### ISSUE THREAD

**Issue by jaliyaudagedara** [microsoft/VS-PPT#248]
I just installed the extension on my Visual Studio Enterprise 2022 Preview (64-bit) Version 17.0.0 Preview 3.1, but I am not seeing the menu item (**Edit** > **Copy Html Markup**)

Visual Studio Version:
```
Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
Version 17.0.0 Preview 3.1
```
![image](https://user-images.githubusercontent.com/5653381/129974506-23682858-e86a-44f2-be0a-5997786e0531.png)

Missing **Copy Html Markup** option
![image](https://user-images.githubusercontent.com/5653381/129974398-2d6cc170-6cd2-47b1-8293-fb35815b9c8a.png)

I can however see the **HTMP Copy** inside **Productivity Power Tools** in **Tools** > **Options**.
![image](https://user-images.githubusercontent.com/5653381/129974631-bb71abc0-caff-4e62-894a-5775b56d1a3b.png)

Please let me know if you need further information/logs. Without this my VS is like incomplete :(

**Comment by ufcpp** [comment]
Same in Version 17.0.0 Preview 4.0

**Comment by simusr2** [comment]
Same for me in Version 17.0.0 Preview 4.1. I installed this extension by installing _Productivity Power Tools 2022_.

**Comment by olegtk** [comment]
Can somebody please file a feedback ticket via Help/Send Feedback/Report a Problem? Thanks!
