### ISSUE TITLE
"Copy as HTML 2022" is broken in 17.9p2

### ISSUE THREAD

**Issue by RussKie** [Microsoft/VS-PPT#269]
![image](https://github.com/microsoft/VS-PPT/assets/4403806/85d3ec04-3b39-4f37-aae4-2fa40bc2f315)

VS: Version 17.9.0 Preview 2.0 [34303.136.main]

An attempt to copy **any** text results in the following error:
![image](https://github.com/microsoft/VS-PPT/assets/4403806/8a4409c3-7172-4fce-b4ab-f47ad1dcb14f)

**Comment by olegtk** [comment]
Thank you for reporting, @RussKie, it should be fixed now in both 17.9 P1 and P2.
