### ISSUE TITLE
Copy As Html doesn't copy C# or F# colour

### ISSUE THREAD

**Issue by ploeh** [Microsoft/VS-PPT#271]
When using the [Copy As Html](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.CopyAsHtml) extension with C#, it no longer includes any colour information.

Let's say I'd like to copy this line of code:
![image](https://github.com/microsoft/VS-PPT/assets/242165/5757cb91-121c-4059-b002-4997ce2777f1)
Using _Edit, Copy Html Markup_, this is what I get:

```html
var&nbsp;zeroes&nbsp;=&nbsp;new&nbsp;byte[k];
```

No colour information about any of the keywords.

The same is true if I try to copy some F# code.

Surprisingly, however, the extension _does_ work with Python code:
![image](https://github.com/microsoft/VS-PPT/assets/242165/2ccdd77c-002d-4f54-b83e-1a6de17f782b)
If I copy this as HTML, I get this:

```html
<span style="color:green;">#!/usr/bin/env&nbsp;python</span>
<span style="color:blue;">import</span>&nbsp;numpy
<span style="color:blue;">import</span>&nbsp;matplotlib.pyplot&nbsp;<span style="color:blue;">as</span>&nbsp;plt
```

Even more surprising, it also works with Haskell, for which I've manually installed a TextMate bundle:
![image](https://github.com/microsoft/VS-PPT/assets/242165/d2bab82e-128c-4394-b3c7-c73aed8801e6)
becomes
```html
<span style="color:#2b91af;">average</span>&nbsp;<span style="color:blue;">::</span>&nbsp;<span style="color:blue;">Integral</span>&nbsp;a&nbsp;<span style="color:blue;">=&gt;</span>&nbsp;<span style="color:blue;">NE</span>.<span style="color:blue;">NonEmpty</span>&nbsp;a&nbsp;<span style="color:blue;">-&gt;</span>&nbsp;a
average&nbsp;nel&nbsp;=&nbsp;<span style="color:blue;">sum</span>&nbsp;nel&nbsp;`div`&nbsp;<span style="color:blue;">fromIntegral</span>&nbsp;(NE.<span style="color:blue;">length</span>&nbsp;nel)
```

Like the OP of #252 I've modified the _BeforeCodeSnippet_ and _AfterCodeSnippet_ options. I've removed both (setting them to blank values), which explains why the generated code has no surrounding `<pre>` tag.

As far as I can tell, it looks as though the languages that have 'native' colouring by Visual Studio somehow break the extension. I haven't tried with Visual Basic, but this seems to apply to both C# and F# in both light and dark mode.

**Comment by ploeh** [comment]
Here's another observation: The setting _UnindentToRemoveExtraLeadingWhitespace_ is set to _True_, which I believe is the default. This setting, however, is not consistently applied.

Here's what I highlight:
![image](https://github.com/microsoft/VS-PPT/assets/242165/0a00c207-3c67-4b82-b3d0-45af77ef7c8b)
Here's what I get:
```html
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;value1&nbsp;=&nbsp;100.00D;
double&nbsp;value2&nbsp;=&nbsp;15.99D;
double&nbsp;result&nbsp;=&nbsp;client.Add(value1,&nbsp;value2);
```

**Comment by ploeh** [comment]
I've managed to reset the extension to use default values (i.e. defaults for _BeforeCodeSnippet_ and _AfterCodeSnippet_), but that doesn't help.

**Comment by BertanAygun** [comment]
Hi @ploeh, can you confirm if you have this option enabled:

`We added support for accurate classification for more accurate colors based on Tools -> Options -> Text Editor -> Advanced -> "Use accurate classifier" setting. Please note that copy operations can be slower when this setting is enabled.`

Thanks,
Bertan

**Comment by ploeh** [comment]
It's getting late here in Copenhagen, so it's possible that I'm just too tired, but where do I find that setting?

![image](https://github.com/microsoft/VS-PPT/assets/242165/231dc8f2-e7c5-42f7-9f64-53c1245fc678)

**Comment by BertanAygun** [comment]
I also just realized that setting no longer exists in product so I will have to investigate and reply back here. 

Thanks,
Bertan

**Comment by olegtk** [comment]
"Use accurate classifier" setting was really bad perf-wise in general case and was removed in 17.9. I suggest either just make CopyAsHTML always call accurate classifier or introduce it's own CopyAsHTML-specific option to control whether to use accurate classification, and make it default.

**Comment by olegtk** [comment]
I have a fix for CopyAsHTML, will push an update soon.
The root cause turned to be this change in Roslyn behavior: https://developercommunity.visualstudio.com/t/ITagAggregatorIClassificationTag-no-lo/10595181

**Comment by ploeh** [comment]
> I have a fix for CopyAsHTML, will push an update soon.

Looking forward to it!

> The root cause turned to be this change in Roslyn behavior: https://developercommunity.visualstudio.com/t/ITagAggregatorIClassificationTag-no-lo/10595181

Ooh, a breaking change in a Microsoft product!

**Comment by ploeh** [comment]
Any news on when we can expect the update?

**Comment by ploeh** [comment]
ping

**Comment by iccfish** [comment]
Seems this extension out of maintenance?

**Comment by heiligerdankgesang** [comment]
Thanks for following up, folks. While we do have a fix, there’s some additional work that needs to be completed before we can update the extension with the fix and make it available for use. We don’t yet have a timeline for release, but please keep an eye on this issue for further updates.

**Comment by ploeh** [comment]
It works again! Thank you; I'm very happy.
