### ISSUE TITLE
The tab header double click to maximize is not working in VS 17.11 Preview 3.0

### ISSUE THREAD

**Issue by egvijayanand** [Microsoft/VS-PPT#272]
The tab header double click to maximize is not working in VS 17.11 Preview 3.0

Kindly look into it.

**Comment by jekelly** [comment]
We're unable to reproduce this.

If you're still having trouble, please [report a problem](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) in VS2022 and provide a recording. If you add a link to your issue here, we'll have a better shot of diagnosing.

**Comment by egvijayanand** [comment]
Here's the linked issue:

https://developercommunity.visualstudio.com/t/Restore-tab-header-double-click-to-maxim/10698759

Now updated to VS2022 17.11 Preview 7.0, but the issue is still there. Clicking on the Tab header doesn't maximize it.

Check whether it helps and in the meantime will try to record a video.

**Comment by egvijayanand** [comment]
PPT 2022 v17.0 is installed.

It worked previously, but couldn't recollect which exact version was that.

**Comment by jekelly** [comment]
Thanks for the link and context. I'm still unable to reproduce the problem on latest 17.11 build and latest Double-Click Maximize extension.

While a video recording can be useful, it would be more useful if you can follow the steps in the Report a Problem guidance and provide a recording through our feedback tool. This collects additional information about what is happening in VS while you record and will give us more insight into why this may not be working for you.

**Comment by egvijayanand** [comment]
After upgrading to VS2022 17.12 Preview 1.0, this has again started functioning as usual.

VS did something unusual in one of the versions in between.

Thanks for the support. This issue can be marked as resolved.
