### ISSUE TITLE
Ctrl + Click Go To Definition wrongly mapped

### ISSUE THREAD

**Issue by Drakesinger** [Microsoft/VS-PPT#34]
Greetings,
In the current release for VS2015 v14.0.23120.0 the Ctrl + Click Go To Definition option is mapped to "Peek Definition".
This is not the same as "Go To Definition" which is by default mapped to the F12 key.

**Comment by olegtk** [comment]
That's right. If you prefer F12 behavior, you can switch Ctrl+Click to that using Tools/Options/productivity Power Tools/Other Extensions/Control Click Shows Definitions in Peek" checkbox.

**Comment by Drakesinger** [comment]
Allright. Thank you.

It is however a bit misleading to put this option so far in the settings.
Maybe move it in the general section?

**Comment by olegtk** [comment]
There is no General section in PPT options :(
Another way to find this option is to search "control click" in Tools/Options or QuickLaunch (Ctrl+Q).
Unless somebody cares a lot about this, I'm going to close this issue. Thanks!

**Comment by Drakesinger** [comment]
I meant the "Turn Extensions On/Off" screen by "General". But yeah, not very important to move it.
Thanks for the solution.
