### ISSUE TITLE
Feature request: sort selected lines

### ISSUE THREAD

**Issue by LegalizeAdulthood** [Microsoft/VS-PPT#38]
Many times while working in C++ projects I want to sort my include directives:

```
#include <windows.h>
#include <tchar.h>
```
becomes
```
#include <tchar.h>
#include <windows.h>
```
There are many other occasions when working with text files where sorting the selected lines would be very handy as well.

Give me a command that will take the selected lines in the text editor and sort them.

**Comment by justcla** [comment]
This is a great suggestion. I can see how useful it would be.

But right now we are not looking to implement any new features into PPT.
This could be developed as separate, stand-alone extension.

Thanks for the suggestion!

**Comment by justcla** [comment]
I'm closing this issue as we won't be implementing this.

**Comment by LegalizeAdulthood** [comment]
Where can I read about why PPT isn't accepting new features?  I kinda thought that was the whole point of being on github...

**Comment by justcla** [comment]
The [Roadmap](https://github.com/Microsoft/VS-PPT/wiki/Roadmap) states:

> At this point in time, we're working on the following activities:
> 1. quality / infrastructure improvements and bug fixes - see below (open for contributions)
> 2. open sourcing the remaining Productivity Power Tools extensions that aren't presently in this repo (Microsoft PPT team)
> 3. active feature development (Microsoft PPT team)

And the [Contributions doc](https://github.com/Microsoft/VS-PPT/blob/master/CONTRIBUTING.md) states:

> we're focused for now primarily on quality and infrastructure improvements, along with bug reports and suggestions.

and

> Contributions to the master branch beyond the level of a bug fix are reserved for Microsoft PPT members at this stage.

As for why.... that's not documented. It was a decision made internally and there are several reasons for it. One reason is that we are focusing our efforts in other areas at the moment, so engineering support is not readily available to test, release and support new features developed by the community. Another reason is that we are looking to phase out the Productivity Power Tools (in their current form) as we move the more popular items into the core product.

Brief history: Originally, PPT was a place to trial new/experimental features that had not yet made it into the core product. But over time people came to rely on these features (which had no official support model). We are looking at a new form of delivering experimental features in the future.

**The main point** of being on GitHub is to provide sample code for developers who want to see real world examples of how to extend Visual Studio.
A secondary purpose is to allow developers to make their own modifications for their own needs.
And finally, it's an avenue for the community to provide bug fixes and tests for the existing features.

When it comes to developing new features, we recommend creating a new VSIX (Visual Studio extension) for each new feature. You can then put the extension on the Gallery for others to download - without any need for Microsoft to test/release/support your new feature.

Hope that helps.

**Comment by LegalizeAdulthood** [comment]
Thanks for that explanation!
