### ISSUE TITLE
Brace Lines

### ISSUE THREAD

**Issue by dev-cdd** [Microsoft/VS-PPT#39]
Running Visual Studio 2015 Update 3... sometime after Update 3 the lines drawn between braces... isn't displaying anymore.

I've disabled/re-enabled addons, removed all but PPT... nothing works.
[VS2015ActivityLog.zip](https://github.com/Microsoft/VS-PPT/files/369296/VS2015ActivityLog.zip)

**Comment by ltrzesniewski** [comment]
The structure visualizer doesn't display anything in the scrollbar BTW in Update 3. The scrollbar gets thicker when the option is enabled, but that's about it.

**Comment by dev-cdd** [comment]
This is what I'm talking about:
![example](https://cloud.githubusercontent.com/assets/222110/16921470/ac1ac8fc-4cdf-11e6-92fb-e9ec8c1ae35a.png)

Strangely enough, after repairing Visual Studio... it works for every file... except one (granted I haven't opened EVERY file, but various files I've opened, the lines are drawn in all of them -- except for one).

**Comment by Boredbone** [comment]
I encountered the same problem.
Perhaps, expression-bodied properties (like `public int X => 0;`) cause it.

**Comment by xmarshal** [comment]
Same problem with  expression-bodied properties in file.

**Comment by Kiwibomber** [comment]
same problem here:
![error](https://cloud.githubusercontent.com/assets/18040502/17132456/256cfc1e-5322-11e6-8495-528526e4afc7.png)

MS VS Pro 2015 Version 14.0.25422.01 Update 3

**Comment by dev-cdd** [comment]
Confirmed -  expression body is the breaker.

**Comment by xmarshal** [comment]
expression body for props but not for methods.

**Comment by LMLB** [comment]
Can you update the extension in the gallery as well?
