### ISSUE TITLE
Sort by Most Recently Used - Why default?

### ISSUE THREAD

**Issue by dsaf** [Microsoft/VS-PPT#41]
Why would you make something like this a default setting?

http://stackoverflow.com/questions/38391613/active-tab-fixed-to-the-left-in-visual-studio

http://stackoverflow.com/questions/38465816/visual-studio-active-tab-moves-left

**Comment by justcla** [comment]
We are putting out a batch that makes the default OFF for this sorting feature.

**Comment by dsaf** [comment]
Thank you!

**Comment by justcla** [comment]
An update has been released that has the Most Recently Used setting defaulting to OFF.
UPDATED 7/25/2016
VERSION 14.0.24321.0

**Comment by dsaf** [comment]
Thanks!
