### ISSUE TITLE
Custom Document Well - "Place tabs on the left" and pinned tabs behavior

### ISSUE THREAD

**Issue by th3ragex** [Microsoft/VS-PPT#58]
With the Custom Document Well option set to Left:
(Productivity Power Tools 2015, VS2015 Update 3)

![cdwleft](https://cloud.githubusercontent.com/assets/15040273/18378937/2a0f5124-7670-11e6-8b99-80774067102e.png)

pinned tabs use more space than necessary by introducing a second column:

![cdwpinnedtab](https://cloud.githubusercontent.com/assets/15040273/18378996/71485e46-7670-11e6-9e3a-06d01cabdf22.png)

Is this intended?

I prefer the previous version where the pinnded tabs were placed directly above each other.
(The following screenshot is from Productivity Power Tools 2012)

![cdwpinnedtab_old](https://cloud.githubusercontent.com/assets/15040273/18379098/ea6946dc-7670-11e6-9580-d603e87bc9fc.png)

**Comment by th3ragex** [comment]
Moved to a new PC with fresh installation of VS15 and everything works as expected. Pinned tabs are placed above not pinned tabs.

Closing this issue since it seems to be a strange configuration / upgrade problem.

**Comment by studnia** [comment]
This is caused by "Show pinned tabs in a separate row" option in Tools -> Options -> Environment -> Tabs and Windows
