### ISSUE TITLE
CopyAsHTML should use the html5 doctype

### ISSUE THREAD

**Issue by mgradwohl** [Microsoft/VS-PPT#6]
`97     @"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4.0 Transitional//EN"">`

should be
`<!DOCTYPE html>`

per [https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Introduction_to_HTML5](url)

**Comment by AlexEyler** [comment]
Great idea - anyone want to take this? Would be a great first PR :smile: https://github.com/Microsoft/VS-PPT/blob/a243e09441d29b9f4c42f4a4ea653329dd8ca8d7/src/CopyAsHtml/CopyAsHtml/ClipboardSupport.cs line 97

**Comment by mgradwohl** [comment]
Working on it now.

**Comment by mgradwohl** [comment]
#8

**Comment by olegtk** [comment]
Merged #8. Thanks!
