### ISSUE TITLE
VS2015 ignoring PPT settings

### ISSUE THREAD

**Issue by asherber** [Microsoft/VS-PPT#62]
My installation of PPT in VS2015 has started ignoring its settings. For example, I have Custom Document Well and Syntactic Line Compression turned off, but those extensions are still running (i.e., tabs appear colored and braces appear smaller).

I have tried restarting VS, as well as uninstalling and reinstalling PPT.

**Comment by LWChris** [comment]
Wait, you uninstalled PPT and the tabs are still colored!?
Appears to me you have another add-on that colors the tabs.

**Comment by asherber** [comment]
Uninstalled and then reinstalled -- trying to clear out any kind of detritus from a previous install. If I uninstall and leave it uninstalled, the tabs are not colored.

**Comment by LWChris** [comment]
I just disabled the Custom Document Well, restarted VS and it stayed off, and my tabs are not colored.

**Comment by asherber** [comment]
I am closing this issue. For the record, I have been using PPT in some form for years. In VS2015, it was working as expected on all three of my machines, until it started misbehaving on just one of my machines a few weeks ago. I'm sure it was some settings file that got "stuck" somehow and was hoping for some pointers on where to look.

In the meantime, after some combination of uninstall/reinstall/restart VS/reboot Windows, it is now working again.
