### ISSUE TITLE
Column guides can't be turned off

### ISSUE THREAD

**Issue by jbaute** [Microsoft/VS-PPT#68]
Hi,

I turned off column guides in the options, but I keep seeing them in the editor, even after restarting VS.
![2016-11-29 11_33_13-options](https://cloud.githubusercontent.com/assets/10774709/20706459/c0c22b2c-b627-11e6-8de3-c83f7e749457.png)

**Comment by olegtk** [comment]
@jbaute, those lines are created by the Structure Visualizer extension, not by Column Guides. I know it's confusing indeed.

**Comment by jbaute** [comment]
Hehe, ok. I figured I was doing it wrong. :)
Thx!
