### ISSUE TITLE
Installing Ctrl+Click Go to definition gives error

### ISSUE THREAD

**Issue by Frankwin** [Microsoft/VS-PPT#75]
When installing the Ctrl+Click Go TO Definition plugin I get an error.

Here's the install.log
1/18/2017 10:06:50 AM - Microsoft VSIX Installer
1/18/2017 10:06:50 AM - -------------------------------------------
1/18/2017 10:06:50 AM - vsixinstaller.exe version:
1/18/2017 10:06:50 AM - 15.0.26020.0 built by: D15REL
1/18/2017 10:06:50 AM - -------------------------------------------
1/18/2017 10:06:50 AM - Command line parameters:
1/18/2017 10:06:50 AM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\frank\Downloads\CtrlClickGoToDef (1).vsix
1/18/2017 10:06:50 AM - -------------------------------------------
1/18/2017 10:06:50 AM - Microsoft VSIX Installer
1/18/2017 10:06:50 AM - -------------------------------------------
1/18/2017 10:06:50 AM - Initializing Install...
1/18/2017 10:06:51 AM - Extension Details...
1/18/2017 10:06:51 AM - 	Identifier         : CtrlClickGoToDefn.b66d9c08-a6c6-4fbf-9827-ba4693968419
1/18/2017 10:06:51 AM - 	Name               : Ctrl+Click Go To Definition
1/18/2017 10:06:51 AM - 	Author             : Microsoft
1/18/2017 10:06:51 AM - 	Version            : 2.0
1/18/2017 10:06:51 AM - 	Description        : Make ctrl+click perform a "Go To Definition" on the identifier under the cursor.
Also, when the ctrl key is held down, highlight identifiers that look like they have definitions to navigate to.
1/18/2017 10:06:51 AM - 	Locale             : en-US
1/18/2017 10:06:51 AM - 	MoreInfoURL        : http://blogs.msdn.com/noahric
1/18/2017 10:06:51 AM - 	InstalledByMSI     : False
1/18/2017 10:06:51 AM - 	SupportedFrameworkVersionRange : [4.5,)
1/18/2017 10:06:51 AM - 
1/18/2017 10:06:51 AM - 	SignatureState     : ValidSignature
1/18/2017 10:06:51 AM - 	SignedBy           : Microsoft Corporation
1/18/2017 10:06:51 AM - 	Certificate Info   : 
1/18/2017 10:06:51 AM - 		-------------------------------------------------------
1/18/2017 10:06:51 AM - 		[Subject]       : CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
1/18/2017 10:06:51 AM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
1/18/2017 10:06:51 AM - 		[Serial Number] : 33000000FF6B54F91DD1781A1C0000000000FF
1/18/2017 10:06:51 AM - 		[Not Before]    : 2/11/2016 6:12:29 PM
1/18/2017 10:06:51 AM - 		[Not After]     : 5/11/2017 7:12:29 PM
1/18/2017 10:06:51 AM - 		[Thumbprint]    : 6F1691367DB1D2F6278B8A82A1C4095D3BC0AF1C
1/18/2017 10:06:51 AM - 
1/18/2017 10:06:51 AM - 	Supported Products : 
1/18/2017 10:06:51 AM - 		Microsoft.VisualStudio.Community
1/18/2017 10:06:51 AM - 			Version : [15.0]
1/18/2017 10:06:51 AM - 
1/18/2017 10:06:51 AM - 	References         : 
1/18/2017 10:06:51 AM - 		-------------------------------------------------------
1/18/2017 10:06:51 AM - 		Identifier   : PPTOptionsPage.666715a6-3ac4-4bb7-b538-4d7625f99666
1/18/2017 10:06:51 AM - 		Name         : Productivity Power Tools Options Page
1/18/2017 10:06:51 AM - 		Version      : [2.0,3.0)
1/18/2017 10:06:51 AM - 		MoreInfoURL  : 
1/18/2017 10:06:51 AM - 		Nested       : Yes
1/18/2017 10:06:51 AM - 
1/18/2017 10:06:51 AM - 	Prerequisites      : 
1/18/2017 10:06:51 AM - 		-------------------------------------------------------
1/18/2017 10:06:51 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/18/2017 10:06:51 AM - 		Name         : Visual Studio core editor
1/18/2017 10:06:51 AM - 		Version      : [15.0.25904.2,16.0)
1/18/2017 10:06:51 AM - 
1/18/2017 10:06:51 AM - Signature Details...
1/18/2017 10:06:51 AM - 	Extension is signed with a valid signature.
1/18/2017 10:06:51 AM - 
1/18/2017 10:06:51 AM - Searching for applicable products...
1/18/2017 10:06:51 AM - Found installed product - Global Location
1/18/2017 10:06:51 AM - Found installed product - Visual Studio Community 2017 RC
1/18/2017 10:06:52 AM - The extension with ID 'CtrlClickGoToDefn.b66d9c08-a6c6-4fbf-9827-ba4693968419' is not installed to Visual Studio Community 2017 RC.
1/18/2017 10:06:55 AM - The following target products have been selected...
1/18/2017 10:06:55 AM - 	Visual Studio Community 2017 RC
1/18/2017 10:06:55 AM - 
1/18/2017 10:06:56 AM - Beginning to install extension to Visual Studio Community 2017 RC...
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:56 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:06:57 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
1/18/2017 10:06:57 AM - Install Error : Microsoft.VisualStudio.ExtensionManager.NestedExtensionInstallException: The extension 'PPTOptionsPage.666715a6-3ac4-4bb7-b538-4d7625f99666' nested within 'CtrlClickGoToDefn.b66d9c08-a6c6-4fbf-9827-ba4693968419' failed to install.
Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.RefreshExtractedPackageStream(IInstalledExtension parentExtension, IExtensionReference reference)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformLegacyInstall(InstallableExtensionImpl extension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Boolean isPackComponent, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by DoCode** [comment]
same here
+1

**Comment by justcla** [comment]
What configuration are you running?
What workloads (or components) are installed on the instance you're running?

**Comment by Frankwin** [comment]
Just Windows 10 w/ Visual Studio 2017 RC. I'm not sure what you mean w/ workloads (or components)?

**Comment by PhilBarila** [comment]
@Frankwin, workloads are the large feature sets in the installer.  On my Enterprise installer, as I write this, I see 3 workloads inside the _Windows_ box.  **Universal Windows Platform development**, **.NET desktop development**, and **Desktop development with C++**.  Then there are a bunch under _Web and Cloud_, and 5 under _Mobile and Gaming_, and then there are two more under _Other Toolsets_.
I have all the _Windows_ workloads, **Mobile development with .NET (Preview)**, **Mobile development with C++**, and **Linux development with C++**.

**Comment by Frankwin** [comment]
@PhilBarila Thank you.

I have  the following Workloads installed:

Windows 
- Universal Windows Development
- .NET desktop development
- Desktop development with C+

Web & Cloud
- Web development
- Azure development
- Python development (preview)
- Node.js development
- Data storage and processing
- Data science and analytical applications (preview)
- .NET Core and Docker

Mobile & Gaming
- Mobile Development with .NET (Preview)
- Game development with Unity
- Mobile Development with Javascript
- Mobile Development with C++
- Game development with C++

Other Toolsets
- Visual Studio Extension Development
- Linux development with C++

**Comment by justcla** [comment]
Duplicate issue - [Nested Extensions not working pre RC3](https://github.com/Microsoft/VS-PPT/issues/77).
