### ISSUE TITLE
Installing Syntactic Line Compression plugin gives error

### ISSUE THREAD

**Issue by Frankwin** [Microsoft/VS-PPT#76]
Installing this plugin gives and error. Here's the install.log

1/18/2017 10:19:37 AM - Microsoft VSIX Installer
1/18/2017 10:19:37 AM - -------------------------------------------
1/18/2017 10:19:37 AM - vsixinstaller.exe version:
1/18/2017 10:19:37 AM - 15.0.26020.0 built by: D15REL
1/18/2017 10:19:37 AM - -------------------------------------------
1/18/2017 10:19:37 AM - Command line parameters:
1/18/2017 10:19:37 AM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\frank\Downloads\SyntacticLineCompression.vsix
1/18/2017 10:19:37 AM - -------------------------------------------
1/18/2017 10:19:37 AM - Microsoft VSIX Installer
1/18/2017 10:19:37 AM - -------------------------------------------
1/18/2017 10:19:37 AM - Initializing Install...
1/18/2017 10:19:38 AM - Extension Details...
1/18/2017 10:19:38 AM - 	Identifier         : SyntacticLineCompression.4452fb8f-b348-49eb-9499-76669d3f9c75
1/18/2017 10:19:38 AM - 	Name               : Syntactic Line Compression
1/18/2017 10:19:38 AM - 	Author             : Microsoft
1/18/2017 10:19:38 AM - 	Version            : 2.0
1/18/2017 10:19:38 AM - 	Description        : This extension shrinks lines that contain neither text nor numbers so that more lines can be displayed in the editor.
1/18/2017 10:19:38 AM - 	Locale             : en-US
1/18/2017 10:19:38 AM - 	MoreInfoURL        : 
1/18/2017 10:19:38 AM - 	InstalledByMSI     : False
1/18/2017 10:19:38 AM - 	SupportedFrameworkVersionRange : [4.5,)
1/18/2017 10:19:38 AM - 
1/18/2017 10:19:38 AM - 	SignatureState     : ValidSignature
1/18/2017 10:19:38 AM - 	SignedBy           : Microsoft Corporation
1/18/2017 10:19:38 AM - 	Certificate Info   : 
1/18/2017 10:19:38 AM - 		-------------------------------------------------------
1/18/2017 10:19:38 AM - 		[Subject]       : CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
1/18/2017 10:19:38 AM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
1/18/2017 10:19:38 AM - 		[Serial Number] : 33000000FF6B54F91DD1781A1C0000000000FF
1/18/2017 10:19:38 AM - 		[Not Before]    : 2/11/2016 6:12:29 PM
1/18/2017 10:19:38 AM - 		[Not After]     : 5/11/2017 7:12:29 PM
1/18/2017 10:19:38 AM - 		[Thumbprint]    : 6F1691367DB1D2F6278B8A82A1C4095D3BC0AF1C
1/18/2017 10:19:38 AM - 
1/18/2017 10:19:38 AM - 	Supported Products : 
1/18/2017 10:19:38 AM - 		Microsoft.VisualStudio.Community
1/18/2017 10:19:38 AM - 			Version : [15.0]
1/18/2017 10:19:38 AM - 
1/18/2017 10:19:38 AM - 	References         : 
1/18/2017 10:19:38 AM - 		-------------------------------------------------------
1/18/2017 10:19:38 AM - 		Identifier   : PPTOptionsPage.666715a6-3ac4-4bb7-b538-4d7625f99666
1/18/2017 10:19:38 AM - 		Name         : Productivity Power Tools Options Page
1/18/2017 10:19:38 AM - 		Version      : [2.0,3.0)
1/18/2017 10:19:38 AM - 		MoreInfoURL  : 
1/18/2017 10:19:38 AM - 		Nested       : Yes
1/18/2017 10:19:38 AM - 
1/18/2017 10:19:38 AM - 	Prerequisites      : 
1/18/2017 10:19:38 AM - 		-------------------------------------------------------
1/18/2017 10:19:38 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/18/2017 10:19:38 AM - 		Name         : Visual Studio core editor
1/18/2017 10:19:38 AM - 		Version      : [15.0.25904.2,16.0)
1/18/2017 10:19:38 AM - 
1/18/2017 10:19:38 AM - Signature Details...
1/18/2017 10:19:38 AM - 	Extension is signed with a valid signature.
1/18/2017 10:19:38 AM - 
1/18/2017 10:19:38 AM - Searching for applicable products...
1/18/2017 10:19:38 AM - Found installed product - Global Location
1/18/2017 10:19:38 AM - Found installed product - Visual Studio Community 2017 RC
1/18/2017 10:19:39 AM - The extension with ID 'SyntacticLineCompression.4452fb8f-b348-49eb-9499-76669d3f9c75' is not installed to Visual Studio Community 2017 RC.
1/18/2017 10:19:42 AM - The following target products have been selected...
1/18/2017 10:19:42 AM - 	Visual Studio Community 2017 RC
1/18/2017 10:19:42 AM - 
1/18/2017 10:19:43 AM - Beginning to install extension to Visual Studio Community 2017 RC...
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:43 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:19:44 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
1/18/2017 10:19:44 AM - Install Error : Microsoft.VisualStudio.ExtensionManager.NestedExtensionInstallException: The extension 'PPTOptionsPage.666715a6-3ac4-4bb7-b538-4d7625f99666' nested within 'SyntacticLineCompression.4452fb8f-b348-49eb-9499-76669d3f9c75' failed to install.
Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.RefreshExtractedPackageStream(IInstalledExtension parentExtension, IExtensionReference reference)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformLegacyInstall(InstallableExtensionImpl extension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Boolean isPackComponent, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by AlcatrazDev** [comment]
Having this issue as well, the only extension i've been able to install was FixMixedTabs

**Comment by DoCode** [comment]
same here
+1

**Comment by justcla** [comment]
What configuration are you running?
What workloads (or components) are installed on the instance you're running?

**Comment by Frankwin** [comment]
Just Windows 10 w/ Visual Studio 2017 RC. I'm not sure what you mean w/ workloads (or components)?

**Comment by Frankwin** [comment]
I have  the following Workloads installed:

Windows 
- Universal Windows Development
- .NET desktop development
- Desktop development with C+

Web & Cloud
- Web development
- Azure development
- Python development (preview)
- Node.js development
- Data storage and processing
- Data science and analytical applications (preview)
- .NET Core and Docker

Mobile & Gaming
- Mobile Development with .NET (Preview)
- Game development with Unity
- Mobile Development with Javascript
- Mobile Development with C++
- Game development with C++

Other Toolsets
- Visual Studio Extension Development
- Linux development with C++

**Comment by justcla** [comment]
Duplicate issue - [Nested Extensions not working pre RC3](https://github.com/Microsoft/VS-PPT/issues/77).
