### ISSUE TITLE
Nested Extensions not working pre RC3  (Time Stamp Margin Plugin gives error on install)

### ISSUE THREAD

**Issue by Frankwin** [Microsoft/VS-PPT#77]
The Time Stamp Margin Plugin gives an error on install. Here's the install.log

1/18/2017 10:21:12 AM - Microsoft VSIX Installer
1/18/2017 10:21:12 AM - -------------------------------------------
1/18/2017 10:21:12 AM - vsixinstaller.exe version:
1/18/2017 10:21:12 AM - 15.0.26020.0 built by: D15REL
1/18/2017 10:21:12 AM - -------------------------------------------
1/18/2017 10:21:12 AM - Command line parameters:
1/18/2017 10:21:12 AM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\frank\Downloads\TimeStampMargin.vsix
1/18/2017 10:21:12 AM - -------------------------------------------
1/18/2017 10:21:12 AM - Microsoft VSIX Installer
1/18/2017 10:21:12 AM - -------------------------------------------
1/18/2017 10:21:12 AM - Initializing Install...
1/18/2017 10:21:12 AM - Extension Details...
1/18/2017 10:21:12 AM - 	Identifier         : TimeStampMargin.255e8b14-4a53-4eb7-89a7-7ab741c1f612
1/18/2017 10:21:12 AM - 	Name               : Time Stamp Margin
1/18/2017 10:21:12 AM - 	Author             : Microsoft
1/18/2017 10:21:12 AM - 	Version            : 2.0
1/18/2017 10:21:12 AM - 	Description        : This extension adds a time stamp margin to the debug output window.
1/18/2017 10:21:12 AM - 	Locale             : en-US
1/18/2017 10:21:12 AM - 	MoreInfoURL        : 
1/18/2017 10:21:12 AM - 	InstalledByMSI     : False
1/18/2017 10:21:12 AM - 	SupportedFrameworkVersionRange : [4.5]
1/18/2017 10:21:12 AM - 
1/18/2017 10:21:12 AM - 	SignatureState     : ValidSignature
1/18/2017 10:21:12 AM - 	SignedBy           : Microsoft Corporation
1/18/2017 10:21:12 AM - 	Certificate Info   : 
1/18/2017 10:21:12 AM - 		-------------------------------------------------------
1/18/2017 10:21:12 AM - 		[Subject]       : CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
1/18/2017 10:21:12 AM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
1/18/2017 10:21:12 AM - 		[Serial Number] : 33000000FF6B54F91DD1781A1C0000000000FF
1/18/2017 10:21:12 AM - 		[Not Before]    : 2/11/2016 6:12:29 PM
1/18/2017 10:21:12 AM - 		[Not After]     : 5/11/2017 7:12:29 PM
1/18/2017 10:21:12 AM - 		[Thumbprint]    : 6F1691367DB1D2F6278B8A82A1C4095D3BC0AF1C
1/18/2017 10:21:12 AM - 
1/18/2017 10:21:12 AM - 	Supported Products : 
1/18/2017 10:21:12 AM - 		Microsoft.VisualStudio.Community
1/18/2017 10:21:12 AM - 			Version : [15.0]
1/18/2017 10:21:12 AM - 
1/18/2017 10:21:12 AM - 	References         : 
1/18/2017 10:21:12 AM - 		-------------------------------------------------------
1/18/2017 10:21:12 AM - 		Identifier   : PPTOptionsPage.666715a6-3ac4-4bb7-b538-4d7625f99666
1/18/2017 10:21:12 AM - 		Name         : Productivity Power Tools Options Page
1/18/2017 10:21:12 AM - 		Version      : [2.0,3.0)
1/18/2017 10:21:12 AM - 		MoreInfoURL  : 
1/18/2017 10:21:12 AM - 		Nested       : Yes
1/18/2017 10:21:12 AM - 
1/18/2017 10:21:12 AM - 	Prerequisites      : 
1/18/2017 10:21:12 AM - 		-------------------------------------------------------
1/18/2017 10:21:12 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/18/2017 10:21:12 AM - 		Name         : Visual Studio core editor
1/18/2017 10:21:12 AM - 		Version      : [15.0.25904.2,16.0)
1/18/2017 10:21:12 AM - 
1/18/2017 10:21:12 AM - Signature Details...
1/18/2017 10:21:12 AM - 	Extension is signed with a valid signature.
1/18/2017 10:21:12 AM - 
1/18/2017 10:21:12 AM - Searching for applicable products...
1/18/2017 10:21:12 AM - Found installed product - Global Location
1/18/2017 10:21:12 AM - Found installed product - Visual Studio Community 2017 RC
1/18/2017 10:21:13 AM - The extension with ID 'TimeStampMargin.255e8b14-4a53-4eb7-89a7-7ab741c1f612' is not installed to Visual Studio Community 2017 RC.
1/18/2017 10:21:34 AM - The following target products have been selected...
1/18/2017 10:21:34 AM - 	Visual Studio Community 2017 RC
1/18/2017 10:21:34 AM - 
1/18/2017 10:21:35 AM - Beginning to install extension to Visual Studio Community 2017 RC...
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:35 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/18/2017 10:21:36 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
1/18/2017 10:21:36 AM - Install Error : Microsoft.VisualStudio.ExtensionManager.NestedExtensionInstallException: The extension 'PPTOptionsPage.666715a6-3ac4-4bb7-b538-4d7625f99666' nested within 'TimeStampMargin.255e8b14-4a53-4eb7-89a7-7ab741c1f612' failed to install.
Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.RefreshExtractedPackageStream(IInstalledExtension parentExtension, IExtensionReference reference)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformLegacyInstall(InstallableExtensionImpl extension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Boolean isPackComponent, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by DoCode** [comment]
same here
+1

**Comment by justcla** [comment]
What configuration are you running?
What workloads (or components) are installed on the instance you're running?

**Comment by Frankwin** [comment]
Just Windows 10 w/ Visual Studio 2017 RC. I'm not sure what you mean w/ workloads (or components)?

**Comment by Dany-R** [comment]
I get (applies also to **SyntacticLineCompression** and **MatchMargin**)
> Microsoft.VisualStudio.ExtensionManager.NestedExtensionInstallException: Error installing the Extension "PPTOptionsPage.666715a6-3ac4-4bb7-b538-4d7625f99666", nested into "TimeStampMargin.255e8b14-4a53-4eb7-89a7-7ab741c1f612" (translated from German)
> and also a NullReferenceException

Installed on Win10 Pro x64: Enterprise 15.0.26020.0 .NET-Desktop Development, Desktop Development with C++, VS Extension Development and some optional Components (would be helpful to have a "report Components to Clipboard").

**Comment by Frankwin** [comment]
I have  the following Workloads installed:

Windows 
- Universal Windows Development
- .NET desktop development
- Desktop development with C+

Web & Cloud
- Web development
- Azure development
- Python development (preview)
- Node.js development
- Data storage and processing
- Data science and analytical applications (preview)
- .NET Core and Docker

Mobile & Gaming
- Mobile Development with .NET (Preview)
- Game development with Unity
- Mobile Development with Javascript
- Mobile Development with C++
- Game development with C++

Other Toolsets
- Visual Studio Extension Development
- Linux development with C++

**Comment by justcla** [comment]
The bug we're seeing with this and the other three extensions that nest the options page is a known issue for RC.2 that is fixed in RC.3. (15.0.26110.0 and above)

**Comment by verysimplenick** [comment]
same, maybe can say when 15.0.26110.0 be available? :)

**Comment by justcla** [comment]
Until RC3 is available, I will un-publish the items from the Marketplace.

**Comment by justcla** [comment]
Until the fix for Nested Extensions is publicly available in RC3, I have removed the PPTOptionsPage extension from each of the four failing extensions and made it available as a separately downloadable/installable extension.
PPT Options Page: [https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProductivityPowerToolsOptionsPage](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProductivityPowerToolsOptionsPage)

I have re-published the four extensions:
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.CopyAsHtml
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MatchMargin
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.SyntacticLineCompression
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.TimeStampMargin

**Comment by Dany-R** [comment]
Great, works like a charm! Thank you for your support Justin 👍

**Comment by Dany-R** [comment]
BTW, why is the "More information" link missing in extension browser for all Power Tools?

**Comment by justcla** [comment]
@Dany-R Ah, that's because at the time I created them, the URL on the Marketplace did not exist (chicken and egg). So now that they have valid Marketplace IDs, I'll link them up. Thanks for the reminder!

**Comment by justcla** [comment]
All More Info links have been updated. Thanks for the tip.
