### ISSUE TITLE
Solution Error Visualizer does "not load correctly"

### ISSUE THREAD

**Issue by Dany-R** [Microsoft/VS-PPT#79]
Starting VS2017 I always get a message that this extension did not load correctly because there is no **SolutionErrorFilter.dll**.
The activity log states (sorry for the German but I cannot uninstall this language)
> CreateInstance failed for package [ErrorFilterPackage]Source: &apos;mscorlib&apos; Description: Die Datei oder Assembly &quot;file:///C:\Users\Dany\AppData\Local\Microsoft\VisualStudio\15.0_32765d1f\Extensions\ynjgttaw.lz4\SolutionErrorFilter.dll&quot; oder eine Abh&#x00E4;ngigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.&#x000D;&#x000A;System.IO.FileNotFoundException: Die Datei oder Assembly &quot;file:///C:\Users\Dany\AppData\Local\Microsoft\VisualStudio\15.0_32765d1f\Extensions\ynjgttaw.lz4\SolutionErrorFilter.dll&quot; oder eine Abh&#x00E4;ngigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.&#x000D;&#x000A;File name: &apos;file:///C:\Users\Dany\AppData\Local\Microsoft\VisualStudio\15.0_32765d1f\Extensions\ynjgttaw.lz4\SolutionErrorFilter.dll&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;=== Zustandsinformationen vor Bindung ===&#x000D;&#x000A;LOG: Where-ref-Bindung. Speicherort = C:\Users\Dany\AppData\Local\Microsoft\VisualStudio\15.0_32765d1f\Extensions\ynjgttaw.lz4\SolutionErrorFilter.dll&#x000D;&#x000A;LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/&#x000D;&#x000A;LOG: Urspr&#x00FC;nglicher PrivatePath = NULL&#x000D;&#x000A;Aufruf von Assembly : (Unknown).&#x000D;&#x000A;===&#x000D;&#x000A;LOG: Diese Bindung startet im LoadFrom-Load-Kontext.&#x000D;&#x000A;WRN: Das systemeigene Image wird nicht im LoadFrom-Kontext durchsucht. Das systemeigene Image wird nur im Standard-Load-Kontext durchsucht, z. B. Assembly.Load().&#x000D;&#x000A;LOG: Die Anwendungskonfigurationsdatei wird verwendet: C:\Users\Dany\AppData\Local\Microsoft\VisualStudio\15.0_32765d1f\devenv.exe.config&#x000D;&#x000A;LOG: Die Hostkonfigurationsdatei wird verwendet: &#x000D;&#x000A;LOG: Die Computerkonfigurationsdatei von C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config wird verwendet.&#x000D;&#x000A;LOG: Download von neuem URL file:///C:/Users/Dany/AppData/Local/Microsoft/VisualStudio/15.0_32765d1f/Extensions/ynjgttaw.lz4/SolutionErrorFilter.dll.&#x000D;&#x000A;

**Comment by stoberman37** [comment]
I am getting the same error.  I'm able to browse to folder and decompile the assembly via dotPeek, so I'm not sure what's going on.  This occurs when starting VS 2017 RC in administrator mode as well.  The English output from the activity log is as follows:

CreateInstance failed for package [ErrorFilterPackage]Source: 'mscorlib' Description: Could not load file or assembly 'file:///C:\Users\scottob\AppData\Local\Microsoft\VisualStudio\15.0_270b9e01\Extensions\uq2ivubd.qeu\SolutionErrorFilter.dll' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Users\scottob\AppData\Local\Microsoft\VisualStudio\15.0_270b9e01\Extensions\uq2ivubd.qeu\SolutionErrorFilter.dll' or one of its dependencies. The system cannot find the file specified. File name: 'file:///C:\Users\scottob\AppData\Local\Microsoft\VisualStudio\15.0_270b9e01\Extensions\uq2ivubd.qeu\SolutionErrorFilter.dll' at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark) at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence) at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo) at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by justcla** [comment]
There is an error in the pkgdef file (SolutionErrorFilter.pkgdef).
The executable was previously named SolutionErrorFilter.dll and after renaming it for this release, the pkgdef file was not updated.
Checked in update to SolutionErrorFilter.pkgdef
Now pointing to
`"CodeBase"="$PackageFolder$\SolutionErrorVisualizer.dll"`

**Comment by DoCode** [comment]
@justcla And where you checked this changes in?

**Comment by Dany-R** [comment]
@justcla Thank you, but I'd also like to know, where you checked it in?
This repository seems to hold the old VS2015 sources but the issue tracker is also used for (and linked by) the new split extensions. Are the new extensions closed source?

**Comment by olegtk** [comment]
@Dany-R this repo is slightly out sync with released extensions. There were some project and vsix manifest changes (not functional changes) facilitating upgrade to VS 2017. We will merge them back to this repo once migration is complete. This repro will always contain the sources for the latest release.

There were also significant internal changes, we finally moved official PPT build to a modern build server and can finally use nuget packages.

**Comment by justcla** [comment]
I have uploaded a new version of the extension with the fix in the pgkdef file.
Please try again.
Thanks

**Comment by Dany-R** [comment]
@justcla Thank you, now there is no startup-error anymore.

Sandly, as stated before, the extension loads but when I hover on a green or red squiggled entry in Solution Explorer, VS crashes ("not working anymore" and "sending a crash report"). :(
