### ISSUE TITLE
Unable to change keyboard binding on "More Commands for Navigation"

### ISSUE THREAD

**Issue by karlmarxman** [Microsoft/VS-PPT#92]
Feature: "Using Ctrl+Alt+Page Down and Page Up to navigate between tabs (including pinned) in visual order.
Activate a specific pinned tab by Ctrl+Num Pad 1 through 0
Activate a specific regular tab by Ctrl+Alt+Num Pad 1 through 0 "

is not available for binding in either the Power Tools menu or listed in the Options/Keyboard commands. Is it possible for this to be added? I don't have number pad keys so would prefer to bind it to something else.

**Comment by justcla** [comment]
Hi Karl

I can confirm that Ctrl+Alt+PgUp/PgDn does navigate between tabs. This behavior is included in Visual Studio core.
If you want to remap the keys for it, use:
- Window.NextTab
- Window.PreviousTab

Thanks for the tips about Ctrl+1-0 and Ctrl+Alt+1-0.
I never knew those features existed! But I'm glad you pointed them out.
Like you said, I cannot find these bindings in Tools->Options->Keyboard.

I have discovered these are features of Custom Document Well.
(It seems they are undocumented.)

These are great shortcuts and have been much requested.
Specifically, people have asked to use Ctrl+1-0 to go directly to numbered tabs.
So I agree, it would be better if these commands were exposed and mappable.

I'll see what I can do about that.

**Comment by justcla** [comment]
I have made a change to [Custom Document Well 2017](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.CustomDocumentWell) that exposes the commands for Window.GoToPinnedTab1-10 and Window.GoToUnpinnedTab1-10.

![image](https://cloud.githubusercontent.com/assets/17131343/22909798/1801a11e-f20b-11e6-8303-7ebb9828e6f1.png)

This will be uploaded to Marketplace when it has passed testing. Look for version 15.0.1

**Comment by karlmarxman** [comment]
Just upgraded to VS 2017 and this works perfectly. Thanks!
